### ISSUE TITLE
fsleye volume rendering opacity correction

### ISSUE THREAD

**Issue by neurolabusc** [pauldmccarthy/fsleyes#1]
1. There seems to be something wrong with the alpha values passed to the volume renderer. All non-air voxels seem to have values near 1 (completely opaque). Typically, dark voxels that have a brightness near the air-tissue boundary should be more transparent than brighter voxels. To demonstrate, one can see a dramatic improvement in rendering quality if you set the alpha to be the luminance of the red green and blue components. An ideal solution would be a user selectable function - e.g. a single slider could set the alpha to [Perlin's bias function](https://blog.demofox.org/2012/09/24/bias-and-gain-are-your-friend/) of the voxel intensity relative to the display range (the luminance trick will fail with some color maps). Alternatively, you could have something like MRIcroGL's Color/ColorEditor function where the user can interactively adjust the alpa of each node of the color scheme.
2. You may want to have the blendFactor modulated or set by rayStep- in the code below I use the traditional Opacity Correction factor from page 219 of Engel et al's "Real-Time Volume Graphics".

To generate the image shown below edit glvolume_3d_frag.glsl:

//new code
colour.a = dot(colour.rgb, vec3(0.299, 0.587, 0.114));
colour.a = 1.0-pow((1.0 - colour.a), blendFactor);
colour.rgb *= colour.a;
finalColour += (1.0 - finalColour.a) * colour; //accumulate color
//old code
//finalColour.rgb += (1 - finalColour.a) * blendFactor * colour.rgb;
//finalColour.a   += (1 - finalColour.a) * blendFactor;

![fsleyes](https://user-images.githubusercontent.com/8930807/39657570-0cf544d0-4fd7-11e8-9bbc-d3a4dc53bdd8.png)

**Comment by pauldmccarthy** [comment]
Hi @neurolabusc, thanks for the suggestion - this improves the rendering quite a lot. I will adjust this in the next version.

At this point in time I am not sure how much flexibility I want to add to the FSLeyes 3D view.  Obviously I would like users to be able to make nice images/overlays. but I certainly don't want to re-invent the wheel by emulating MRIcroGL. Basic 3D rendering -> FSLeyes; Advanced 3D rendering -> MRIcroGL :)

**Comment by neurolabusc** [comment]
Great, I look forward to the next release. I understand your concerns - there is a constant battle between adding features and making a tool overwhelming. On the other hand, MRIcroGL is released with the MIT license, so you have the opportunity to steal (er... leverage) existing code without having to reinvent it. Further, if we do use similar shaders developers and users can share ideas between the code.

The next versions of MRIcroGL and Surfice will provide the user with the option to use Python for the scripting language, so there could be a convergence of sorts.

**Comment by pauldmccarthy** [comment]
For 0.24.3 (just released), I've taken your advice and modulated the opacity of each sample by the voxel intensity, and also applied the opacity correction as described in Engel et. al. Rendering now looks much better - thanks!

There's still a bit of work to do w.r.t. overlay blending. If I can, I would like to avoid having to render multiple overlays in a single shader pass as this doesn't really fit with the internal data model used by FSLeyes (although I could re-arrange things if needed). So when I find some time, I am planning to experiment with some alternate approaches (e.g. tricks using the Z-buffer) to try and improve the rendering of multiple overlays.
