### ISSUE TITLE
AttributeError: type object 'OverlayList' has no attribute 'AtlasPanel_140482816957744'

### ISSUE THREAD

**Issue by jaguarxp82** [pauldmccarthy/fsleyes#102]
Using FSL 6.0.5, when I open FSLeyes, and try overlay an atlas on a standard space "MNI_*". I get this error which I assume that it is due to incompatible versions of fsleyes and fsleyes_props. It is worth noting that in older versions, it was working fine.
![fsleyes_HL](https://user-images.githubusercontent.com/15674955/200916488-a31ec39e-6435-4fbe-89c6-d8269f0b9a0e.png)
![error](https://user-images.githubusercontent.com/15674955/200916490-b47a0cb6-b337-46f8-85e9-dc5b06eaed1b.png)

**Comment by pauldmccarthy** [comment]
This problem will be resolved if you update to the latest available version of FSLeyes - you can do so via this command:

```
sudo $FSLDIR/fslpython/bin/conda update -n fslpython -c conda-forge --update-all fsleyes
```
