### ISSUE TITLE
Unable to interact with the nudge window

### ISSUE THREAD

**Issue by swatijain2789** [pauldmccarthy/fsleyes#110]
Hi Paul, 

I am using windows 11 (x64) with WSL2 and Ubuntu 18.04.5 version. After much issues, I managed to get fsleyes to run (I have downloaded x11 and VcXsrv as well. The glxgears test GUI would run well prior to fsl installation and once I installed fsleyes, it would stop running. So after installing x11 and VcXsrv it runs, including the bash command export DISPLAY=:0 prior to that. 

Now while running fsleyes, I can't interact with any of the nudge windows when I open. Any ideas?

Thank you. 

Regards, 

Swati

**Comment by pauldmccarthy** [comment]
Hi @swatijain2789, sorry for the delay. All I can suggest here is that you try a different X server, e.g. mobaxterm, xming, or the built-in Windows 11 Wayland server.
