### ISSUE TITLE
color bar not displaying when using command line

### ISSUE THREAD

**Issue by burdinskid13** [pauldmccarthy/fsleyes#111]
I am trying to follow the steps in this recent tweet: https://twitter.com/ten_photos/status/1670507166283845632

I would like to use fsleyes in the command line. I tried to use the code from tweet as suggested here: https://gist.github.com/nicholst/009b22b9a6f94d93ed50fb27ea6f0f82

I added the color bar option as suggested and my final code (with my threshold added) looks like this: 

fsleyes render --showColourBar --colourBarLocation right --colourBarLabelSide top-left \
  $Anat \
  $Effect \
   --cmap red-yellow --negativeCmap blue-lightblue --useNegativeCmap \
   --modulateAlpha --modulateImage $Stat --modulateRange 0.0 14 \
  $Stat --overlayType mask --outline \
   --threshold -2.26 2.26

The command works (the visualization looks correct), but the color bar is not shown in the out.png file. Could you please help?

**Comment by pauldmccarthy** [comment]
Hi @burdinskid13, can I ask what version of FSLeyes you are using? You can find out in the _FSLeyes->About_ menu option, or by running `fsleyes -V` from a terminal.

**Comment by pauldmccarthy** [comment]
Aah, I've just noticed that @nicholst has solved this issue for you (https://gist.github.com/nicholst/009b22b9a6f94d93ed50fb27ea6f0f82?permalink_comment_id=4615985#gistcomment-4615985)
