### ISSUE TITLE
Request: ability to click a timeseries plot and skip to that volume

### ISSUE THREAD

**Issue by CGSchwarzMayo** [pauldmccarthy/fsleyes#113]
Hi Paul,
Our group is getting ready to migrate from fslview to fsleyes for routine image QC. It's been a long time in coming. One thing we noticed is a loss of functionality (from fslview) in the timeseries view. In fslview, a user could click on the plot in the timeseries view, and the linked volume view would skip to that particular volume on the x axis. Click+drag would move through the volumes as the mouse moved along the x axis. In fsleyes, this isn't supported. Clicking on the plot does nothing, and click+drag slides the plot around. It was a handy little shortcut to quickly investigate spikes in the plot to see what happened, vs. in fsleyes one has to guess "that spike looks like it's around volume 120-130 somewhere", then go scroll until they find it. 

Would this functionality be reasonable to add, or are such interactions with the plot not reasonable within the current plotting frameworks?

Thanks,
Chris

**Comment by pauldmccarthy** [comment]
Hi @CGSchwarzMayo, you should be able to cmd/ctrl+click on the time series plot to shift to that volume; most of the shortcuts built into FSLeyes are listed at https://open.win.ox.ac.uk/pages/fsl/fsleyes/fsleyes/userdoc/keyboard_shortcuts.html#plotting-views

**Comment by CGSchwarzMayo** [comment]
Paul,
I apologize that I hadn't thought to check for keyboard modifiers! It didn't work how fslview did, so I improperly assumed that it wasn't there. Thanks for your fast response!
