### ISSUE TITLE
Python debugger error when starting on Fsl 1.7.0  

### ISSUE THREAD

**Issue by Amjadhpc** [pauldmccarthy/fsleyes#115]
Hello

I am seeing this error whenever i start fsleyes  that has been installed using fsl 1.7.0  fslinstaller.

fsleyes
Failed to establish dbus connection0.03s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.

What does this error mean and how can it be turned off ?

**Comment by pauldmccarthy** [comment]
HI @Amjadhpc, this is coming from the Python interpreter, and has nothing to do with FSLeyes. It is nothing to worry about, and will be filtered in the next FSLeyes release.
