### ISSUE TITLE
GLXBadContext error

### ISSUE THREAD

**Issue by yummyspringroll** [pauldmccarthy/fsleyes#119]
Hi, I'm using a linux subsystem (Ubuntu 18.04.6) on windows
I get this error:

The program 'fsleyes' received an X Window System error.

> This probably reflects a bug in the program.
> The error was 'GLXBadContext'.
>   (Details: serial 693 error_code 156 request_code 148 minor_code 6)
>   (Note to programmers: normally, X errors are reported asynchronously;
>    that is, you will receive the error a while after causing it.
>    To debug your program, run it with the --sync command line
>    option to change this behavior. You can then get a meaningful
>    backtrace from your debugger if you break on the gdk_x_error() function.)

The output of glxgears is:

> X Error of failed request:  GLXBadContext
>   Major opcode of failed request:  148 (GLX)
>   Minor opcode of failed request:  6 (X_GLXIsDirect)
>   Serial number of failed request:  25
>   Current serial number in output stream:  24

The output of glxinfo is:

> name of display: :0.0
> X Error of failed request:  GLXBadContext
>   Major opcode of failed request:  148 (GLX)
>   Minor opcode of failed request:  6 (X_GLXIsDirect)
>   Serial number of failed request:  39
>   Current serial number in output stream:  38

I installed fsleyes through conda, but I can’t check my version of wxpython by typing conda list. It’s not in the list.

I’m using VcXsrv.

What should I do?
Thanks!

**Comment by pauldmccarthy** [comment]
Hi @yummyspringroll, there are a few notes about setting up VcXsrv in the FSL installation instructions at https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/FslInstallation/Windows#System_Requirements

-  When running XLaunch, it is critical to deselect _Native OpenGL_ and select _Disable access control_ in the Extra Settings panel. 
- In order for VcXsrv to work, you will need to add these lines to your .bashrc file. Copy+paste the following lines into the Ubuntu shell:
  ```
  echo "export DISPLAY=\$(grep nameserver /etc/resolv.conf  | awk '{print \$2; exit}'):0" >> ~/.bashrc
  echo "export LIBGL_ALWAYS_INDIRECT=0" >> ~/.bashrc 
  ```

- For Windows 11 you will also need to add run an additional command:
  ```
  echo "export LIBGL_ALWAYS_SOFTWARE=1" >> ~/.bashrc
  ```

Every system is different, so if the above doesn't work, try experimenting with the `LIBGL_ALWAYS_INDIRECT` and `LIBGL_ALWAYS_SOFTWARE` environment variables, as they may or may not be required for your system.

**Comment by yummyspringroll** [comment]
Thank you so much!! I tried again and the problem solved. I can launch fsleyes now. Thank you so much for your support. Wish you have a good day!
