### ISSUE TITLE
FSLeyes on WSL 2

### ISSUE THREAD

**Issue by sh-shahrokhi** [pauldmccarthy/fsleyes#122]
Hello,

I installed FSL on a WSL 2 system, based on instructions from FSL wiki.
I am able to launch FSLeyes, and it works. however, when I open the 'view settings' window, the items are not selectable and I can't even close that window without quiting FSLeyes.
Could you please help with that? I can provide log files if needed.

Thanks

**Comment by pauldmccarthy** [comment]
Hi @sh-shahrokhi, I'm guessing you're using the wayland server which is built into WSL2 - this is a [known issue](https://github.com/microsoft/wslg/issues/948) without any resolution as far as I'm aware. I'd recommend using a separate X11 server such as vcxsrv or mobaxterm.

**Comment by pauldmccarthy** [comment]
This should be resolved as of FSLeyes 1.12.1 (and it should be possible to use FSLeyes with the built-in Wayland server).
