### ISSUE TITLE
FSL install error in maxOS14.0

### ISSUE THREAD

**Issue by voxel77** [pauldmccarthy/fsleyes#124]
Hi

I followed the steps on the FSL website to install (My macOS version is 14.0, but FSL offers versions up to 13)
`python3 fslinstaller.py`

And installation failed, 
`This command returned an error: /Users/hyf/fsl/bin/mamba env update -n base -f /private/var/folders/6r/fg89lrc13glcq3dcf6q3q3880000gn/T/tmpv_1ztw4q/fsl-6.0.7.4_macos-M1.yml`

The log file showed that there were many compressed packages that had not been extracted, e.g.
`01:28:36 fslinstaller.py: 937:  [stderr]: error    libmamba Error opening for reading "/Users/hyf/fsl/pkgs/fsl-cudimot-2006.0-0/info/index.json": No such file or directory
01:28:36 fslinstaller.py: 937:  [stderr]: error    libmamba Error when extracting package: [json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - unexpected end of input; expected '[', '{', or a literal`

How do I solve this problem？

**Comment by pauldmccarthy** [comment]
Hi @voxel77 the [FSL mailing list](https://www.jiscmail.ac.uk/cgi-bin/webadmin?A0=FSL) is the best place to ask FSL questions. But are you able to share the log file that the fslinstaller saved?

**Comment by voxel77** [comment]
> Hi @voxel77 the [FSL mailing list](https://www.jiscmail.ac.uk/cgi-bin/webadmin?A0=FSL) is the best place to ask FSL questions. But are you able to share the log file that the fslinstaller saved?
Thanks for your suggestion, and there is my log file.
[fsl_installation_20231028030309.log](https://github.com/pauldmccarthy/fsleyes/files/13212858/fsl_installation_20231028030309.log)
