### ISSUE TITLE
1.9.0 requires unreleased fsleyes-props >= 1.11.1

### ISSUE THREAD

**Issue by sanjayankur31** [pauldmccarthy/fsleyes#125]
https://github.com/pauldmccarthy/fsleyes/blob/2cb58cdc1422c7e7a9d88df34da04a85560741b5/pyproject.toml#L19C3-L19C26

or

https://git.fmrib.ox.ac.uk/fsl/fsleyes/fsleyes/-/blob/2cb58cdc1422c7e7a9d88df34da04a85560741b5/pyproject.toml#L19
^
While updating the Fedora packages, I noticed that fsleyes requires `fsleyes-props >= 1.11.1`, but that hasn't been released yet.

https://git.fmrib.ox.ac.uk/fsl/fsleyes/props/-/tags

So, one cannot install v1.9.0 at the moment. Would there be an ETA for 1.11.1 please (or is this a typo and should we tweak it to 1.11.0 downstream)?

**Comment by pauldmccarthy** [comment]
Hi @sanjayankur31, I don't quite follow - `fsleyes-props` is pinned at `>=1.11`, not `>=1.11.1`; the latest released version is 1.11.0, so there shouldn't be any problem?

**Comment by sanjayankur31** [comment]
Yeh, you're right. I don't know how/why I came to this conclusion---perhaps our downstream dependency generator had a hiccup, or I was just low on caffeine.. I'll go fix things now. Sorry about that.
