### ISSUE TITLE
tksurfer (FreeSurfer) error - 'command not found'

### ISSUE THREAD

**Issue by voxel77** [pauldmccarthy/fsleyes#126]
When I enter `tksurfer` in the terminal, an error is reported:
`zsh: command not found: tksurfer`

But `recon-all` can run normally. What is the reason for this?

**Comment by pauldmccarthy** [comment]
This sounds like a configuration error in your shell environment, and is probably better directed to the FreeSurfer team: https://surfer.nmr.mgh.harvard.edu/fswiki/FreeSurferSupport

**Comment by voxel77** [comment]
> This sounds like a configuration error in your shell environment, and is probably better directed to the FreeSurfer team: https://surfer.nmr.mgh.harvard.edu/fswiki/FreeSurferSupport

OK！Thank you very much!
