### ISSUE TITLE
4D image Issue

### ISSUE THREAD

**Issue by tblazey** [pauldmccarthy/fsleyes#134]
Hi,

I'm having issues with FSLeyes displaying some 4D images incorrectly. The error seems to be similar to this  [FSL mailing list issue](https://www.jiscmail.ac.uk/cgi-bin/wa-jisc.exe?A2=ind1906&L=FSL&P=R91889&X=E9ED3A9A7564C3E18E&Y=blazey%40artsci.wustl.edu) from a few years ago. I only see a few  slices separated by a large gap.

![artifact](https://github.com/pauldmccarthy/fsleyes/assets/810152/6202c848-fcad-4037-904c-e35323a89061)

 If I specify a specific frame with the -v option it works correctly (though changing frames reintroduces the issue). My setup is as follows:

FSLeyes version: 1.10.2
OpenGL version: 4.1
OpenGL compatibility: 3.3
OpenGL renderer: Intel(R) UHD Graphics 617
Mac OS X 14.2.1

Thanks!

-Tyler

P.S. Sorry for posting here instead of the FSL mailing list. I was having issues posting there.

**Comment by pauldmccarthy** [comment]
Hi @tblazey, would you be able to share this image file with me? I can set up a private upload folder if necessary.

**Comment by pauldmccarthy** [comment]
@tblazey FWIW this should be resolved as of version 1.12.3
