### ISSUE TITLE
Bug for scan colourmaps?

### ISSUE THREAD

**Issue by tomfrankkirk** [pauldmccarthy/fsleyes#136]
When calling colourmaps.init() I get the error 
```
File /opt/homebrew/Caskroom/miniforge/base/envs/qasl/lib/python3.11/site-packages/fsleyes/colourmaps.py:252, in _getMapDirs(subDir)
AttributeError: module 'fsl.utils.settings' has no attribute 'settings'
```
Do I need to be calling some fslpy code first? I would like to access fsleyes colourmaps to use in some plots I am preparing.

**Comment by pauldmccarthy** [comment]
Hi @tomfrankkirk, it's a bit confusing, but you need to initialise the `fsl.utils.settings` module before you can use the `fsleyes.colourmaps` module, e.g.:

```
import fsl.utils.settings as settings
import fsleyes.colourmaps as colourmaps

settings.initialise('fsleyes')
colourmaps.init()
```

The `fsl.utils.settings` module is used for e.g. storing user-added colourmaps in a configuration directory - you can read more about it [here](https://open.win.ox.ac.uk/pages/fsl/fslpy/fsl.utils.settings.html). The parameters given to `settings.initialise` are passe  through to [`Settings.__init__`](https://open.win.ox.ac.uk/pages/fsl/fslpy/fsl.utils.settings.html#fsl.utils.settings.Settings.__init__).

**Comment by tomfrankkirk** [comment]
Thanks Paul for explaining!
