### ISSUE TITLE
FSleyes not opening 

### ISSUE THREAD

**Issue by jigiCS50** [pauldmccarthy/fsleyes#139]
Hi 

I tried to open some files I had converted to nifti but nothing is really opening? The FSLeyes viewer starts and then disappears again when i open it? The file is called 7T_firstscan and then I will want to try and open specific scans eg 7Tfirstscan_ciss_20240517102646_9a.nii but then it will not work? 

jigimoudgil@MacBook-Pro-5 7T_firstscan % fsleyes 7Tfirstscan_ciss_20240517102646_9a.nii
unrecognized arguments: 7Tfirstscan_ciss_20240517102646_9a.nii
FSLeyes version 1.10.2
Usage: fsleyes [options] file [displayOpts] file [displayOpts] ...

Unsure what the unrecognised arguments thing is here... any advice? new to all this

Jigi

**Comment by pauldmccarthy** [comment]
Hi Jigi, the error message suggests that you are not specifying the path to your image file correctly - can you double check that the file exists, that you are in the correct directory, and you have typed its name correctly?
