### ISSUE TITLE
tests/test_addmaskdataseries.py::test_MaskDialog  hangs

### ISSUE THREAD

**Issue by TheChymera** [pauldmccarthy/fsleyes#14]
When running the test suite on `=fsleyes-0.27.3`  with:

```
pytest -v
```

the `tests/test_addmaskdataseries.py::test_MaskDialog` hangs or at least takes over an hour. Judging by `top` this doesn't seem like a memory leak, but other than that I have no idea.

It's also not the only test doing this, `tests/test_resample.py::test_ResampleDialog` also hangs.

**Comment by pauldmccarthy** [comment]
Hey @TheChymera, honestly, I wouldn't bother trying to fix these - as I've explained previously, the test environment is extremely flaky - wxpython and gtk2 both behave inconsistently enough on a system with a display, let alone when running headless within a docker container. Furthermore, the UI event simulator that is used to drive the tests is just as flaky.

I use the unit tests as a sanity check during development - I've spent way too much time debugging problems like this, and unfortunately do not have the time to ensure that they work on every single platform out there. So I would honestly recommend that you don't bother running these tests.

**Comment by TheChymera** [comment]
@pauldmccarthy ok, I totally understand. Is there any blacklist of tests which you could single out for me? Many of the tests still run, and it would be great to at least provide those :)

**Comment by TheChymera** [comment]
Or rather, can you confirm my blacklist? on `0.27.3` these are the tests that hang, and which I opt to remove:

```
    rm tests/test_addmaskdataseries.py
    rm tests/test_embed.py
    rm tests/test_overlay_displayprops.py
    rm tests/test_resample.py
```

Beyond that I just get the failing tests from https://github.com/paualdmccarthy/fsleyes/issues/16 . As you can see, the vast majority of tests pass, ideally we wouldn't need to give up on all.

**Comment by pauldmccarthy** [comment]
The tests that I value the most are the `test_overlay_*.py` tests, as they cover the opengl rendering code. But some of them are hanging/failing for you. Have you tried running the tests in batche (i.e. across multiple invocations of `pytest`)? Because that may help with the tests which hang.

**Comment by TheChymera** [comment]
I don't think I understand what batche is. Do you have any example for how I could invoke that?

**Comment by pauldmccarthy** [comment]
"Batche" was a typo - I meant "batches". Simply calling different batches/groups of tests across multiple invocations of pytest, similar to how my own CI machinery does things: https://github.com/pauldmccarthy/fsleyes/blob/master/.ci/test_template.sh#L68
