### ISSUE TITLE
Assertion errors when testing fsleyes-0.27.3

### ISSUE THREAD

**Issue by TheChymera** [pauldmccarthy/fsleyes#16]
In addition to the [tests which hang](https://github.com/pauldmccarthy/fsleyes/issues/14), a number of tests proceed to fail: 
[build.log](https://github.com/pauldmccarthy/fsleyes/files/3010654/build.log).

**Comment by pauldmccarthy** [comment]
This log file looks like it's from `scikit-image` or `scikit-learn`? But see my reply to #14

**Comment by TheChymera** [comment]
Sorry, I clicked the wrong log, this is the correct [build.log](https://github.com/pauldmccarthy/fsleyes/files/3014392/build.log).
