### ISSUE TITLE
Plugin development question: changing colour maps

### ISSUE THREAD

**Issue by Stoyan-I-A** [pauldmccarthy/fsleyes#17]
Hello,
I am developing a plugin for FSLeyes and I have a few questions.

1- Is it okay if I ask those type of questions here? I used the mailing list before, but I feel like the mailing list is more appropriate for regular users rather than developers.

2- How can I change the colour mapping of an overlay? When the function `overlayList.append(anOverlay)` is used, the overlay has a grayscale colour mapping by default. I would like to change the colour mapping to something like `red` or `blue` directly within my plugin script.

I have more questions, but I will ask them in different issues if I get a confirmation that I can use this platform. 

Sincerely,
Stoyan

**Comment by pauldmccarthy** [comment]
Hey @Stoyan-I-A, you can change an image's colour map like so:

```python
img = Image('my_image.nii.gz')
overlayList.append(img)

display = displayCtx.getDisplay(img)
```

**Comment by Stoyan-I-A** [comment]
Thank you for the help!
