### ISSUE TITLE
[Plugin development question] Updating an overlay after modifying its data.

### ISSUE THREAD

**Issue by Stoyan-I-A** [pauldmccarthy/fsleyes#18]
When I change an overlay's data like so :
`anOverlay[1,2,3] = 255 # anOverlay is an Overlay present in the overlayList`
The data of the overlay is changed but the view is not updated. Meaning the [1,2,3] coordinate still displays the old pixel value. How can I update the display?

I did find a workaround by doing `overlayList.remove(anOverlay)` then `overlayList.append(anOverlay)` but there must be a better way to do this.

Sincerely,
Stoyan

**Comment by pauldmccarthy** [comment]
This looks like a bug - is any error printed anywhere?

I'll try and fix it for the next release - in the meantime, you might have success by changing your code to the following:

```python
anOverlay[1:2, 2:3, 3:4] = 255
```

**Comment by Stoyan-I-A** [comment]
No, it doesn't show any error message. I tried your fix and it is working, thanks.
Should this issue remain open for now?

**Comment by pauldmccarthy** [comment]
Great - I've fixed the bug, but we may as well leave this issue open until I've released the next version.

**Comment by pauldmccarthy** [comment]
Should be fixed in version 0.28.0
