### ISSUE TITLE
[Plugin development question] - Changing the default dock of a plugin's panel

### ISSUE THREAD

**Issue by Stoyan-I-A** [pauldmccarthy/fsleyes#19]
Hello again,

I am developing a plugin that uses a control panel. Is there a way to change the way the panel is docked when it is initialized?

For instance, when I load the control panel used in the [example plugin](https://github.com/pauldmccarthy/fsleyes/blob/master/tests/testdata/fsleyes_plugin_example/fsleyes_plugin_example/plugin.py), the panel appears at the bottom part of the window :
![Screen Shot 2019-04-04 at 2 18 16 PM](https://user-images.githubusercontent.com/43790661/55579808-1fa74200-56e7-11e9-81ca-104549b5a954.png)

I would like to change it in order to make it appear on the left side of the window :
![Screen Shot 2019-04-04 at 2 18 38 PM](https://user-images.githubusercontent.com/43790661/55579992-83316f80-56e7-11e9-8f6d-d3e5d02a80f1.png)

Sincerely,
Stoyan

**Comment by pauldmccarthy** [comment]
Hey @Stoyan-I-A, currently this is not possible, although it will be easy to add in - I'll make it possible in the next version.

**Comment by Stoyan-I-A** [comment]
Very well, thank you for your reply.
I will keep the issue open.

**Comment by pauldmccarthy** [comment]
In version 0.28.0 I've added a method called `defaultLayout`, which you can override in your plugin control panels, e.g.:

```python
import fsleyes.controls.controlpanel as ctrlpanel
class MyPlugin(ctrlpanel.ControlPanel):
    ...
    @staticmethod
    def defaultLayout():
        return {
            'location' : wx.LEFT,
        }
```

The return value is a dictionary which contains arguments that will ultimately be passed to the `ViewPanel.togglePanel` method - you can read about details on the available options [here](https://git.fmrib.ox.ac.uk/fsl/fsleyes/fsleyes/blob/master/fsleyes/views/viewpanel.py#L260)
