### ISSUE TITLE
Feature request: MacOS Retina display option

### ISSUE THREAD

**Issue by neurolabusc** [pauldmccarthy/fsleyes#2]
The menus and widgets of fsleyes look great on a high-dpi (Retina) MacOS computer. This is enabled with `NSHighResolutionCapable` in the info.plist. However, it would be great if the user had the option to have high-DPI OpenGL views. With MacOS, you need to specifically request this, otherwise the OpenGL graphics will be computed at low resolution. The crucial message is `setWantsBestResolutionOpenGLSurface` while the OpenGL context is active. This [link](https://github.com/tpaviot/pythonocc-core/issues/341) suggests some Python code. This should probably be a user selectable option, as it does make more demands on the GPU. To see the benefit, run [MRIcroGL](https://github.com/neurolabusc/MRIcroGL) or [Surfice](https://github.com/neurolabusc/surf-ice) and select the `Retina Display` checkbox in the Preferences.

**Comment by pauldmccarthy** [comment]
Hey @neurolabusc, great idea - I will add this in to the next version!

**Comment by pauldmccarthy** [comment]
It took a while, but this feature is now available in 0.24.3, just released - thanks!
