### ISSUE TITLE
[Plugin development question] - accessing the OrthoPanel trough a plugin script

### ISSUE THREAD

**Issue by Stoyan-I-A** [pauldmccarthy/fsleyes#20]
Hello again,

I am writing a plugin that operates mostly on 2D images. Therefore, I only need to see the data on the Z canvas. How can I access the OrthoPanel data in order to toggle off the X and Y canvas?

I initially asked this question in my other issue, but it might be simpler to respond separately.

Sincerely,
Stoyan

**Comment by pauldmccarthy** [comment]
Hey @Stoyan-I-A, when your control panel is created, the first argument passed to its `__init__` method is a reference to the ortho panel (an `OrthoPanel` object). So you can save a reference to it, e.g.:

```python
import fsleyes.controls.controlpanel as ctrlpanel

class MyControl(ctrlpanel.ControlPanel):
    def __init__(self, ortho, *args, **kwargs):
        ctrlpanel.ControlPanel.__init__(self, ortho, *args, **kwargs)
        self.ortho = ortho
```

Much of the state of an `OrthoPanel` can be manipulated via a separate object of type `OrthoOpts` - you can access it via the `OrthoPanel.sceneOpts` attribute. Then you can modify the `OrthoPanel` state by changing attributes on the `OrthoOpts` instance, e.g.:

```python
oopts = self.ortho.sceneOpts
oopts.showXCanvas = False
oopts.showYCanvas = False
```

There are also various methods on the `OrthoPanel` class - more details on the `OrthoPanel` and `OrthoOpts` classes can be found here:
  * https://users.fmrib.ox.ac.uk/~paulmc/fsleyes/apidoc/latest/fsleyes.views.orthopanel.html
  * https://users.fmrib.ox.ac.uk/~paulmc/fsleyes/apidoc/latest/fsleyes.displaycontext.orthoopts.html

**Comment by Stoyan-I-A** [comment]
Thank you very much!
