### ISSUE TITLE
Checking older versions of the developer documentation

### ISSUE THREAD

**Issue by Stoyan-I-A** [pauldmccarthy/fsleyes#21]
With the release of FSLeyes  0.28.1, the [developer documentation](https://users.fmrib.ox.ac.uk/~paulmc/fsleyes/apidoc/latest/fsleyes.html) is currently blank. Is there a way to look at older versions of the documentation?

Sincerely,
Stoyan

**Comment by pauldmccarthy** [comment]
This is due to a problem in the documentation generation - it's fixed on the master branch, which you can view here:

https://users.fmrib.ox.ac.uk/~paulmc/fsleyes/apidoc/master/fsleyes.html

**Comment by Stoyan-I-A** [comment]
This seems to be fixed now. 👍
