### ISSUE TITLE
Wayland support

### ISSUE THREAD

**Issue by sanjayankur31** [pauldmccarthy/fsleyes#22]
Possibly related to #12. When running fsleyes on a Wayland system, one gets this error:

```
$ fsleyes
/usr/lib/python3.7/site-packages/fsleyes_props/widgets.py:100: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Iterable
Fatal Error: wxGLCanvas is only supported on X11 currently.  You may be able to
work around this by setting environment variable GDK_BACKEND=x11 before starting
your program.
Fatal Error: wxGLCanvas is only supported on X11 currently.  You may be able to
work around this by setting environment variable GDK_BACKEND=x11 before starting
your program.
   ERROR              main.py  537: initialise      - Unable to initialise OpenGL!
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/fsleyes/gl/__init__.py", line 703, in __createWXGLCanvas
    self.__canvas.SetSize((0, 0))
wx._core.wxAssertionError: C++ assertion "m_widget" failed at ../src/gtk/window.cpp(2857) in DoSetSize(): invalid window

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/fsleyes/main.py", line 534, in initialise
    fslgl.getGLContext(parent=splash, ready=realCallback)
  File "/usr/lib/python3.7/site-packages/fsleyes/gl/__init__.py", line 456, in getGLContext
    thismod._glContext = GLContext(**kwargs)
  File "/usr/lib/python3.7/site-packages/fsleyes/gl/__init__.py", line 597, in __init__
    self.__createWXGLCanvas()
  File "/usr/lib/python3.7/site-packages/fsleyes/gl/__init__.py", line 711, in __createWXGLCanvas
    self.__canvas.SetSize((0, 0))
wx._core.wxAssertionError: C++ assertion "m_widget" failed at ../src/gtk/window.cpp(2857) in DoSetSize(): invalid window
```

As mentioned there, the workaround currently, is to run fsleyes as:

```
GDK_BACKEND=x11 fsleyes
```

There isn't much we can do here apart from wait for wxpython to improve Wayland support, but the issue is worth keeping in mind.

**Comment by pauldmccarthy** [comment]
The latest version of FSLeyes (1.0.3) should work under Wayland. I'll leave this (and related) issue open for a little while just in case any reports come in

**Comment by sanjayankur31** [comment]
Thank you! I've not updated the Fedora package to the latest version yet. I'll do that, test and report back.

**Comment by pauldmccarthy** [comment]
@sanjayankur31 that'd be great - note that this depends on the most recent wxpython release (4.1.1) - i'm not sure if that's already been packaged for Fedora ..

**Comment by sanjayankur31** [comment]
Ah, yes, We're not at 4.1.1. yet:

https://bugzilla.redhat.com/show_bug.cgi?id=1827788

I'll ask the maintainer what their plans for updating it are.

**Comment by pauldmccarthy** [comment]
I think your maintainer may be the same person who made the [relevant changes to wxwidgets](https://github.com/wxWidgets/wxWidgets/blob/master/docs/changes.txt#L281) :)

I'm not particularly knowledgable about all of this, but as I understand it the issue with Wayland support has always been the wxWidgets `GLCanvas` class being tightly coupled to the use of `glx` for OpenGL interaction. As of wxWidgets 3.1.5 (== wxPython 4.1.1 for the official releases), it is now possible to choose between GLX and EGL (a compile-time choice). When EGL is used for initialising OpenGL, the `GLCanvas` should work under Wayland without any need for work-arounds.

**Comment by sanjayankur31** [comment]
Ah, yes :D

That makes sense. I don't know much about the underlying bits either, so I think I'll just wait for the Fedora maintainer to do their thing and update accordingly. :laughing:

**Comment by umgpy** [comment]
Hi all, I am on a Fedora 34 and installed fsleyes with conda but recieved the  following error,


> (/path/home/Software/fsleyes) [user@user ~]$ fsleyes
...
...
...
Traceback (most recent call last):
  File "/path/home/Software/fsleyes/lib/python3.9/site-packages/fsl/utils/idle.py", line 576, in __idleLoop
    task.task(*task.args, **task.kwargs)
  File "/path/home/Software/fsleyes/lib/python3.9/site-packages/fsleyes/gl/__init__.py", line 679, in create
    self.__createWXGLContext()
  File "/path/home/Software/fsleyes/lib/python3.9/site-packages/fsleyes/gl/__init__.py", line 876, in __createWXGLContext
    self.__context = wxgl.GLContext(self.__canvas, **kwargs)
wx._core.wxAssertionError: C++ assertion ""tempContext"" failed at /home/conda/feedstock_root/build_artifacts/wxpython_1616628590026/work/ext/wxWidgets/src/unix/glx11.cpp(498) in wxGLContext(): glXCreateContext failed
The program 'fsleyes' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadValue (integer parameter out of range for operation)'.
  (Details: serial 1058 error_code 2 request_code 150 minor_code 3)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)


From the discussion above I believe it is a fedora related issue?
Thanks

**Comment by sanjayankur31** [comment]
No, it doesn't seem to be. I can run `GDK_BACKEND=x11 fsleyes` just fine here on my Fedora 34 system.

If you use the Fedora package: `sudo dnf install python3-fsleyes` and run into issues, please file bugs on the Fedora bugzilla here: https://bugzilla.redhat.com

For Conda packages, please contact the conda maintainer/provider.

**Comment by umgpy** [comment]
@sanjayankur31 Hi, sorry for the late reply. But with your suggested method it works without any issues.
Thanks for the  help!
