### ISSUE TITLE
[Bug] - FSLeyes cannot display large 2D NIfTI images

### ISSUE THREAD

**Issue by Stoyan-I-A** [pauldmccarthy/fsleyes#23]
I converted a 2D .png image into a NIfTI image using the [NiBabel python package](https://nipy.org/nibabel/) 
The size of the image is 3762 x 2486.

Here is the NIfTI file I am trying to load :
[image.nii.gz](https://github.com/pauldmccarthy/fsleyes/files/3135668/image.nii.gz)

Here is the original .png image :
![image](https://user-images.githubusercontent.com/43790661/57036450-5018c800-6c22-11e9-90dc-e2e9b7d274ea.png)

When I try to load the NIfTi file into FSLeyes, the image appears in the overlay list but it isn't displayed in the ortho view. However, I am able to use the cursor and look at the intensity values of the pixels in the location pannel : 
![Screen Shot 2019-05-01 at 3 11 01 PM](https://user-images.githubusercontent.com/43790661/57036825-6c693480-6c23-11e9-9076-259698fc14b8.png)

I am using FSLeyes 0.28.3. I installed it using a python virtual environment. The following error appears in the console when I try to load the NIfTI image : 
```
File "errorchecker.pyx", line 53, in OpenGL_accelerate.errorchecker._ErrorChecker.glCheckError (src/errorchecker.c:1218)
OpenGL.error.GLError: GLError(
	err = 1281,
	description = b'invalid value',
	baseOperation = glTexImage3D,
	pyArgs = (
		GL_TEXTURE_3D,
		0,
		GL_R8,
		3762,
		2486,
		1,
		0,
		GL_RED,
		GL_UNSIGNED_BYTE,
		None,
	),
	cArgs = (
		GL_TEXTURE_3D,
		0,
		GL_R8,
		3762,
		2486,
		1,
		0,
		GL_RED,
		GL_UNSIGNED_BYTE,
		None,
	),
	cArguments = (
		GL_TEXTURE_3D,
		0,
		GL_R8,
		3762,
		2486,
		1,
		0,
		GL_RED,
		GL_UNSIGNED_BYTE,
		None,
	)
)
```

I tried cropping the .png image into an image of size 1024 x 1024 and converted it into a NIfTI image. I had no problem loading the cropped image.

I tried this with several other images. This bug seems to occur when trying to load NIfTI images that have a dimension that is larger than around 2000 pixels.

The code I use to convert .png images into NIfTI looks like this :
```
import numpy as np
import nibabel as nib
from PIL import Image

imagePath = 'image.png'
img_png = np.asarray(Image.open(imagePath).convert('LA'))
img_png2D = img_png[:, :, 0]
img_NIfTI = nib.Nifti1Image(np.flipud(np.rot90(img_png2D, k=3, axes=(0, 1))), np.eye(4))

# Save the NIfTI image
outFile = 'image.nii.gz'
nib.save(img_NIfTI, outFile, )
```

**Comment by pauldmccarthy** [comment]
It looks like you're running into limits imposd by your graphics card. Even though the image is 2D, FSLeyes stores it as a 3D texture (because in principle, NIfTI images always represent data in some 3D space). On my laptop (NVIDIA GeForce GT 750M), the maximum size of an axis in a 3D texture is 2048:

```
MAX_3D_TEXTURE_SIZE           	2048
```

I could build a solution into FSLeyes to handle images larger than this, but it would be a fair amount of work, and unfortunately I don't get a lot of time to work on FSLeyes-related stuff these days. 

You may have to resort to downsampling your image (or using another tool to view it) for the time being.

**Comment by Stoyan-I-A** [comment]
Alright, I will work around it. Thank you

**Comment by jcohenadad** [comment]
Hi @pauldmccarthy, I was wondering if there was any update on your end regarding the possibility to upload 2D bitmaps? If not, do you have an ETA for implementing this useful feature? The reason I'm asking is because this is currently a bottleneck for our [AxonDeepSeg](https://github.com/neuropoly/axondeepseg) project in which we have developed a nice [plugin](https://github.com/neuropoly/axondeepseg/pull/182#issuecomment-481818675). We are considering dropping FSLeyes for another technology, but it would be a shame because our user base is already comfortable with FSLeyes.

**Comment by pauldmccarthy** [comment]
Hi @jcohenadad, most of my time is being spent on non-FSLeyes stuff at the moment, but I'll try and find time over the next few weeks to add in 2D support.

**Comment by pauldmccarthy** [comment]
@jcohenadad @Stoyan-I-A  I'm getting a bit of time to play with this. My current idea is to allow image files (`.png`, `.jpg`, `.bmp` etc) to be loaded, but internally convert them into 2D NIfTI-2 images. This way the _Nudge_ tool, which already exists, can be used to orient/align the image to some reference overlay.  You'll have the option of saving the image as a NIfTI image (in which case the orientation will be saved alongside the data), or keeping the file in its original format, saving the affine matrix to a text file, then loading/applying it later on.

How does that sound?

**Comment by jcohenadad** [comment]
@pauldmccarthy thank you for following up!  Just to be sure: with transforming the images to 2D NIfTI-2 data, will there still be the requirement to tesselate the images, with the limitation of not being able to load "large" images as discussed [here](https://github.com/pauldmccarthy/fsleyes/issues/23#issuecomment-488609058)? This is currently our main limitation.

**Comment by pauldmccarthy** [comment]
Yes I'll use a 2D texture, so the size limit on conventional hardware will be 16384<sup>2</sup>

**Comment by pauldmccarthy** [comment]
@jcohenadad @Stoyan-I-A making progress (using your histology slice)!

![movie](https://user-images.githubusercontent.com/236128/59732786-ccc33c80-928a-11e9-8af1-dfd4120cf353.gif)

**Comment by pauldmccarthy** [comment]
Version 0.30.0 should now be able to load large 2D images - you can install off pypi/conda-forge, or download pre-built versions from https://users.fmrib.ox.ac.uk/~paulmc/fsleyes/dist/

**Comment by jcohenadad** [comment]
Fantastic news! Thank you so much @pauldmccarthy

**Comment by Stoyan-I-A** [comment]
@pauldmccarthy I get this error when trying to load most 2D images (including the histology image at the top of this issue) : 
![image](https://user-images.githubusercontent.com/43790661/60468360-61cd1a80-9c27-11e9-9632-2309b72adb90.png)

More info:
- My OS is Ubuntu 18.04
- I tried to load the images using the menu-item `file->Add from file`
- I tried both the pre-built installation and the pypi installation
- The only 2D image I was able to load was this one : https://github.com/neuropoly/axondeepseg/blob/master/AxonDeepSeg/data_test/mask.png

**Comment by Stoyan-I-A** [comment]
Also, could it be possible to know the location of the 2D image that was loaded? (Similar to the `dataSource` parameter on existing 3D files.)

**Comment by pauldmccarthy** [comment]
Are you running on a remote server, and connecting via SSH or VNC?

It may be that your environment has quite limited capabilities. Within FSLeyes, could you open the python shell (_View -> Python shell_), and type this:

```
import OpenGL.GL as gl
gl.glGetInteger(gl.GL_MAX_TEXTURE_SIZE)
```

**Comment by Stoyan-I-A** [comment]
```
>>> import OpenGL.GL as gl
>>> gl.glGetInteger(gl.GL_MAX_TEXTURE_SIZE)
16384
```
The size of the image doesn't seem to make a difference. I cropped the histology image to a size of 128x128 pixels and I get the same error. However, I am able to convert the cropped image to a 3D NIfTI file and load it with no problem.

If it helps, I am running Ubuntu 18.04 on a virtual machine.

**Comment by pauldmccarthy** [comment]
Ok, that's good - that means it's probably a bug, rather than a limitation of your system. Would you be able to share an image which fails for you?

**Comment by Stoyan-I-A** [comment]
This is the 128x128 image that I tried to load earlier :
![image_small](https://user-images.githubusercontent.com/43790661/60484273-c9965c00-9c4d-11e9-9c3e-16942d351f06.png)


The [histology image at the top of this issue](https://user-images.githubusercontent.com/43790661/57036450-5018c800-6c22-11e9-90dc-e2e9b7d274ea.png) gives an error as well.


This image fails as well :
![image](https://user-images.githubusercontent.com/43790661/60484667-32320880-9c4f-11e9-83b0-0333bc6a55f4.png)


Finally, [I am linking an image that loads correctly.](https://github.com/neuropoly/axondeepseg/blob/master/AxonDeepSeg/data_test/mask.png)

**Comment by pauldmccarthy** [comment]
Right - I suspected that this was the case. The failing images are single-channel (greyscale) - I only added support for RGB(A) images. I'll fix this in the next week or so.

In the meantime, you should be able to view any of them if you convert them to NIfTI beforehand.

**Comment by Stoyan-I-A** [comment]
I tried to load an RBG image, but I got the same error.
This is the image I tried to load :
![python_logo](https://user-images.githubusercontent.com/43790661/60485743-d36e8e00-9c52-11e9-82a3-263d1245890d.png)

**Comment by pauldmccarthy** [comment]
Hmm, [Pillow](https://python-pillow.org/) (the image io library) seems to be having trouble with that Python image - it appears to be loading it as greyscale (and is thus subject to the same FSLeyes issue as the other images).

In any case, I've fixed the code to work with greyscale images. I'll have a quick play with this image to see if it's something that might be a regular occurence, and will release a new version over the next few days.

**Comment by pauldmccarthy** [comment]
@Stoyan-I-A could you try the latest build, available from https://users.fmrib.ox.ac.uk/~paulmc/fsleyes/dist/ ?

(The fix was to an underlying library, so FSLeyes is still on 0.30.0)

**Comment by Stoyan-I-A** [comment]
@pauldmccarthy Using the latest build, I was able to load every image that I previously tested. However, the images were flipped from left to right.
![image](https://user-images.githubusercontent.com/43790661/60761179-602d9900-a011-11e9-9150-2392c94a0119.png)

**Comment by pauldmccarthy** [comment]
Yep, that's because FSLeyes defaults to displaying images in radiological orientation (left of brain on right of screen). You can change it via the `-no` command-line option, or in the view settings (the spanner button).

**Comment by Stoyan-I-A** [comment]
@pauldmccarthy I think I found another bug. I loaded a 2D image, went into edit mode, created an empty mask that has the dimensions of the 2D image and changed the colour mapping. However, the edit mode didn't seem to work : sometimes I couldn't draw on the mask, sometimes the displayed mask wasn't properly updating. I can't really describe the problem is, but if you try to use the edit mode on an empty 2D mask, you should quickly see some odd behavior.

**Comment by pauldmccarthy** [comment]
I stopped at adding support for large 2D images in edit mode. I'll get around to it for the next version. 

But in the meantime you have many, much more powerful options for editing 2D images and creating masks, such as GIMP and Photoshop.

**Comment by Stoyan-I-A** [comment]
@pauldmccarthy Have you had time to look at the edit mode issue?

**Comment by pauldmccarthy** [comment]
Finally found some time - I should be able to get a new version with 2D editing out next week

**Comment by pauldmccarthy** [comment]
Ok, this should hopefully be fixed in 0.30.1 - try it out at https://users.fmrib.ox.ac.uk/~paulmc/fsleyes/dist/ !

🤞

**Comment by Stoyan-I-A** [comment]
Very nice! I tested it with a few images and it seems to work correctly.

One thing I noticed is that I was unable to access the edit mode when I loaded a 2D bitmap image using the `Add from file` button. However, I could access the edit mode if I converted the 2D image into a NIfTI file using the code shown in the top post of this issue, then loaded the NIfTI file into FSLeyes.

**Comment by pauldmccarthy** [comment]
Support is currently limited to single-channel (greyscale) images, regardless of whether they are bitmaps or NIfTI images. Your image at the top of this page is greyscale, but it is encoded as a three-channel (RGB) image, where the information in each channel is identical. 

Do you have a need to edit multi-channel images? I had assumed that the data you work with would typically be single-channel.

**Comment by Stoyan-I-A** [comment]
No, I don't need to edit multi-channel images. It's just that it is easy to create an empty mask by going into edit mode and clicking on the `Create a mask` button. But ultimately, it's not a big deal.

I will close this issue next week if I don't find any bugs.

Thank you for implementing these changes.

**Comment by jcohenadad** [comment]
thank you so much @pauldmccarthy!! 🥇

**Comment by pauldmccarthy** [comment]
Hmm, so your input data is multi-channel (but generally just a single channel duplicated across R, G, and B), and you'd like to create a single-channel (e.g. normal NIFTI) mask. 

I'm not sure of the value in adding the ability to edit multi-channel images - I imagine that this would be a very niche use case. There is, however, the *Overlay -> Copy* menu option; perhaps I can add support in this dialog to create a single-channel mask from a multi-channel image. 

Maybe I could also add a separate *Copy as mask* (or similarly named) menu option which defaults to creating an empty image, to reduce the number of clicks. How does that sound?

**Comment by Stoyan-I-A** [comment]
> add a separate Copy as mask (or similarly named) menu option which defaults to creating an empty image
I like this idea.

**Comment by Stoyan-I-A** [comment]
I am closing this issue since 2D support is properly implemented.
