### ISSUE TITLE
Line width on Ubuntu

### ISSUE THREAD

**Issue by uhussai7** [pauldmccarthy/fsleyes#26]
Cannot change the line width of dyads on Ubuntu. Tried on a mac and it works, just not on ubuntu. Also, tried this with the latest version available at the time of this post -- didn't work.

**Comment by pauldmccarthy** [comment]
How are you running FSLeyes? Locally, in VM, or over a remote connection (e.g. X11/SSH, VNC, ...)?

Can you post the output of `glxinfo`?

**Comment by uhussai7** [comment]
1) What version of Ubuntu?: Tried 18.04 and 16.04.
2) How are you running FSLeyes? 18.04 Locally, 16.04 VM. 
3) [glxinfo_out.txt](https://github.com/pauldmccarthy/fsleyes/files/3403096/glxinfo_out.txt)

**Comment by pauldmccarthy** [comment]
Wait, I have managed to reproduce this on a fresh 16.04 VM... 

https://stackoverflow.com/questions/34866964/opengl-gllinewidth-doesnt-change-size-of-lines

Running the code from the accepted answer in the FSLeyes python shell:

```
>>> import OpenGL.GL as gl
>>> gl.glGetFloat(gl.GL_ALIASED_LINE_WIDTH_RANGE)
array([1., 1.], dtype=float32)
>>> 
```

So this is a limitation in the GL driver; unfortunately there's nothing that I can do about this in the FSLeyes code.

**Comment by pauldmccarthy** [comment]
FYI I've added a note to my internal issue tracker to rework the line vector rendering to use polygons (or maybe even cylinders) to work around this. But I won't be able to be able to work on this in the short term
