### ISSUE TITLE
Setting displayCtx.location does not work from notebook

### ISSUE THREAD

**Issue by jdoepfert** [pauldmccarthy/fsleyes#31]
I can set the voxel location from the integrated python shell via `displayCtx.location = [150, 100, 100]`. However, the same command issued from the fsleyes notebook does not work.

Additional bug: When I run the above command from the integrated python shell, fsleyes jumps to the location 150, 100, 83 instead of 150, 100, 100:
![image](https://user-images.githubusercontent.com/7914340/66906126-60bdce80-f007-11e9-8379-fd758dc7c636.png)

**Comment by pauldmccarthy** [comment]
First of all, the `displayCtx.location` is not in voxel coordinates - you need to transform the coordinates from voxels into display coordinates, e.g.:

```
opts = displayCtx.getOpts(overlayList[0])
displayCtx.location = opts.transformCoords([150, 100, 100], 'voxel', 'display')
```

Second of all, the notebook is given the parent display context instance; you need to access the display context of a view panel, and set hte location on that, e.g.:
```
displayCtx = frame.viewPanels[0]

...

displayCtx.location = ...
```

**Comment by jdoepfert** [comment]
Thanks for the quick answer! I get `AttributeError: 'OrthoPanel' object has no attribute 'location'` when doing 
```
displayCtx = frame.viewPanels[0]

...

displayCtx.location = ...
```
and I get `AttributeError: 'VolumeOpts' object has no attribute '_NiftiOpts__xforms'` when running
```
opts = displayCtx.getOpts(overlayList[0])
displayCtx.location = opts.transformCoords([150, 100, 100], 'voxel', 'display')
```
(both in the notebook). Maybe it's the version? I am using 0.30.1

**Comment by pauldmccarthy** [comment]
Oops no, I made a mistake in my example code - in the notebook, you need to do this:

```
# get the display context of the ortho panel (i'm 
# assuming that you just have an ortho panel open)
displayCtx = frame.viewPanels[0].displayCtx

# get the VolumeOpts instance corresponding to
# the overlay (I'm assuming you've only got one overlay 
# loaded)
opts = displayCtx.getOpts(overlayList[0])

displayCtx.location = opts.transformCoords([150, 100, 100], 'voxel', 'display')
```

**Comment by jdoepfert** [comment]
great, works like a charm 👍 thx
