### ISSUE TITLE
fsleyes  -nb does not open notebook in current directory

### ISSUE THREAD

**Issue by jdoepfert** [pauldmccarthy/fsleyes#32]
`fsleyes  -nb` does open a notebook server in the home directory rather than in the current directory (as expected from `jupyter notebook`). Furthermore, it would be awesome if you could give it a path of a notebook that would be automatically opened, like `fsleyes  -nb path/to/my/nb.ipynb`

**Comment by jdoepfert** [comment]
unrelated question: can i somehow contribute to this repo via a pull request?

**Comment by jdoepfert** [comment]
thanks, let me know when you want some support on that

**Comment by pauldmccarthy** [comment]
Version 0.32.0 has a new `--notebookFile` option, allowing you to specify a specific notebook to open. It also invokes the server in the current working directory, rather than `$HOME`. Let me know if it's not working for you
