### ISSUE TITLE
How can I specify a custom lookup table using the python kernel/notebook?

### ISSUE THREAD

**Issue by jdoepfert** [pauldmccarthy/fsleyes#35]
I can specify an "label" overlay like so:

```
label_img = overlayList[0]
label_display = displayCtx.getDisplay(label_img)
label_display.overlayType = 'label'
```
and I can chose one of the available lookup tables with `label_display.opts.lut = 'FreeSurferColorLut'`. Is there a possibility to register and select a custom LUT directly from the python interface, e.g. by specifying a dict where the keys are e.g. the voxel values and the values are the rgb colors and the label names:
```
custom_lut = {1: ([r, g, b], "hippocampus_left"), 2: ...}
```
and then passing it to the fsleyes instance?

**Comment by pauldmccarthy** [comment]
The following should do what you want..

1. Create a [`fsleyes.colourmaps.LookupTable`](https://users.fmrib.ox.ac.uk/~paulmc/fsleyes/apidoc/latest/fsleyes.colourmaps.html#fsleyes.colourmaps.LookupTable) instance, giving it a unique name (e.g. `MyCoolLut`), and populating it with your LUT values.

2. Register your `Lookuptable` instance instance via [`fsleyes.colourmaps.registerLookupTable`](https://users.fmrib.ox.ac.uk/~paulmc/fsleyes/apidoc/latest/fsleyes.colourmaps.html#fsleyes.colourmaps.registerLookupTable).

3. Load your image, and get a ref to ist `LabelOpts` instance, and set the `lut` property:
  ```
from fsl.data.image import Image
overlayList.append(Image('my_label_image.nii.gz'))
opts = displayCtx.getOpts(overlayList[0])
opts.lut = 'MyCoolLut'
  ```

**Comment by jdoepfert** [comment]
Thanks for the great explanation. I solved it like so
``` 
import fsleyes
import matplotlib


def load_lookuptable(name, lookuptable):
    lut = fsleyes.colourmaps.LookupTable(name, name)
    for value, (identifier, color) in lookuptable.items():
        lut.insert(value, identifier, matplotlib.colors.to_rgb(color))
    fsleyes.colourmaps.registerLookupTable(lut)


lookuptable = {1: ('class A', 'r'),
               2: ('class B', 'b')}

load_lookuptable('mylut', lookuptable)
label_display.overlayType = 'label'
label_display.opts.lut = 'mylut'
```
