### ISSUE TITLE
Relaxing OpenGL requirements

### ISSUE THREAD

**Issue by guilhermebs** [pauldmccarthy/fsleyes#36]
I'm a developer of [SimNIBS](https://github.com/simnibs/simnibs), a software to simulate electric fields in realistic head models. We are very interested in using FSLeyes for our visualization needs, but ran into a problem. Most of our users are on Windows, and Windows machines often have outdated OpenGL libraries.

Therefore, I would like to help relaxing the OpenGL requirements in FSLeyes. Could you please point me towards where I can start?

**Comment by pauldmccarthy** [comment]
Unfortunately this would be a very difficult task - FSLeyes already works with OpenGL 1.4, which is the first version of OpenGL that supports programmable shaders. I certainly don't have the time to work on supporting any versions of OpenGL older than this - sorry.

**Comment by guilhermebs** [comment]
I understand you are busy, that is why I'm volunteering to do it. I just need some guidance on where to start.

**Comment by pauldmccarthy** [comment]
Honestly, I think you would be in a world of pain if you attempted to add support for OpenGL 1.1 - it would require a huge amount of work to re-write the rendering logic without programmable shaders or off-screen framebuffer objects. It was difficult enough to add support for 1.4 (which I added to support X11/SSH connections to remote servers).

I think, to truly provide support on a wide range of Windows machines, DirectX may be the less painful option. This would still require a large amount of work, but I think it would be technically much more straightforward.

Another option requiring much less (zero) development work - have you considered using the [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/install-win10)? In my limited experience, FSLeyes works just fine on Windows when run via WSL.

Anyway, if you'd like to poke through the FSLeyes code to see for yourself, the relevant bits of code, just for the `volume` overlay type (normal volumetric display), are as follows:

 - [`fsleyes/gl/glvolume.py`](../blob/master/fsleyes/gl/glvolume.py): GL version-independent `GLVolume` class
 - [`fsleyes/gl/gl14/glvolume_funcs.py`](../blob/master/fsleyes/gl/gl14/glvolume_funcs.py): GL version-specific interface
 - [`assets/gl/gl14/glvolume_*.prog`](../blob/master/assets/gl/gl14/): GL shader programs
