### ISSUE TITLE
4 Tests fail with `KeyError`s

### ISSUE THREAD

**Issue by TheChymera** [pauldmccarthy/fsleyes#38]
A few tests are failing on FSLeyes `0.32.0`: [build.log](https://github.com/pauldmccarthy/fsleyes/files/4109518/build.log)

additionally, some tests hang (take more than 2 hours), which I am now excluding from the test suite on Gentoo Linux: [`fsleyes-0.32.0-tests_timeout.patch`](https://github.com/pauldmccarthy/fsleyes/files/4109544/fsleyes-0.32.0-tests_timeout_patch.txt).

**Comment by pauldmccarthy** [comment]
Can you give me a listing of the packages in your python environment? This could be due to a change in numpy (or some other package) that I haven't taken into account.

**Comment by TheChymera** [comment]
@pauldmccarthy what packages specifically should I look for? I'm unsure how to create a dump of all om python packages and their versions. For numpy specifically I am using `1.16.5`, all Python packages are run on Python 3.6.
