### ISSUE TITLE
wxpython requirement and Python version

### ISSUE THREAD

**Issue by TheChymera** [pauldmccarthy/fsleyes#4]
Is the `wxpython` package really required? it seems to not be available for python 3*

Does FSLeyes work with Python 3? All the way up to 3.7?

**Comment by TheChymera** [comment]
Ok, inspected the code, it seems indeed required. I'm still curious about Python compatibility, though.

I can't really test just now, since I have to package a newer wxpython first (and this might take a long while).

**Comment by pauldmccarthy** [comment]
Yes, FSLeyes is built on top of wxpython. FSLeyes will work with python 2.7+wxpython 3.0.2.0, but i would recommend python 3.x+wxpython 4.x.

Also note that there is a good chance I will be dropping support for python 2 in the near future (with the 1.0 release of FSLeyes).
