### ISSUE TITLE
rtree version dependency

### ISSUE THREAD

**Issue by sanjayankur31** [pauldmccarthy/fsleyes#40]
I missed this somehow---is it OK for me to tweak the rtree dependency to `>0.8.3' here also as we've done for fslpy?

**Comment by pauldmccarthy** [comment]
Aah, sorry - I should have realised. I had hoped to do a bugfix fsleyes release this week, but am swamped with other things, and am on holiday next week, so this will have to wait until I'm back in mid-February - sorry.

**Comment by sanjayankur31** [comment]
No worries, there's no hurry. I'll patch the requirement downstream in the meantime if necessary.

**Comment by pauldmccarthy** [comment]
Apologies for the delay - I've fixed this in 0.32.1.

**Comment by sanjayankur31** [comment]
No worries. Thanks for the fix. I'll update the Fedora packages soon!
