### ISSUE TITLE
FSLeyes on a VM loads images but doesn't display them

### ISSUE THREAD

**Issue by pkozh** [pauldmccarthy/fsleyes#42]
Hello, 

I am using FSLeyes version 0.32.0 on a virtual machine (VM workstation player). My data is on an external harddrive connected to the virtual machine, Up until yesterday I was able to load any nii.gz image from the harddrive to FSLeyes and it would be fine. Now all of a sudden FSLeyes loads up the image perfectly fine, I can see the relevant intensities but the image itself is simply not visible. 

![IMG-20200212-WA0014](https://user-images.githubusercontent.com/61047551/74522158-9c639900-4f12-11ea-9da0-f30b3f0c3773.jpg)

I tried copied the files to the VM's desktop and loading them from there, same issue, Any ideas as to why this is suddenly occurring? I was thinking it could've been a graphics card issue, but it was fine since yesterday (my graphics card is GeForce GTX 1660).

**Comment by pauldmccarthy** [comment]
I suspect this is a platform issue - something must have changed in the VM, or in your host OS, since yesterday and today. Have you done an OS/driver update, or anything like that?

**Comment by pauldmccarthy** [comment]
Also, are you sure that the specific image(s) you are trying to view actually contain data? You can find out by checking their histogram.

**Comment by pauldmccarthy** [comment]
Another user who reported having a similar issue was able to solve it by upgrading the installed version of Mesa running these commands in the VM:

```
sudo add-apt-repository ppa:ubuntu-x-swat/updates
sudo apt-get update
sudo apt-get dist-upgrade
```
