### ISSUE TITLE
Segmentation fault during test 

### ISSUE THREAD

**Issue by TheChymera** [pauldmccarthy/fsleyes#44]
I am executing the test suite via `virtx pytest -vv` (virtx creates a virtual X environment for the sandbox), and I get the following [build.log](https://github.com/pauldmccarthy/fsleyes/files/4378187/build.log). 

Any idea what's happening?

**Comment by pauldmccarthy** [comment]
I can't help I'm afraid - as I've already explained to you, the tests are very sensitive to the execution environment - headless execution is flaky at the best of times, and I don't have the time to chase down unit test failures on anything but my own set up.

**Comment by TheChymera** [comment]
No problem, just wanted to keep these things referenced, not least of all so that I find them again if I run into the same issue :)
