### ISSUE TITLE
Filling Function (Bucket) not working on Label Overlay

### ISSUE THREAD

**Issue by Symork** [pauldmccarthy/fsleyes#47]
Hi,
Thank you for your software, it is really helpful in my work. I'm used to draw with Label overlay display and I had an issue for filling my drawings. The bucket button was not working. 

![image](https://user-images.githubusercontent.com/62758207/77906923-149ad980-7289-11ea-9c5b-1a49f147a17d.png)

I solved the problem by modifying your source code in the selection.py file :
In the function selectByValue in the class Selection, I replaced the variable self.__opts by self.__display.opts .

Hoping it will help you

**Comment by pauldmccarthy** [comment]
Thanks for the bug report - I'll fix this in the next version.

The problem is occurring because the `Selection` class does not track changes to the overlay type. You could also avoid the problem by changing the overlay type of your image to "label" *before* entering edit mode.

**Comment by Symork** [comment]
Thank you
