### ISSUE TITLE
FSLeyes does not recognize fmriprep melodic directory

### ISSUE THREAD

**Issue by dmd** [pauldmccarthy/fsleyes#48]
fmriprep creates a "melodic" directory. However, FSLeyes's melodic mode (for displaying spatial patterns, timeseries, and power spectrum for each component) seems to require that that directory be specifically named `melodic.ica` in order for this to work correctly. 

I'm not sure whether fmriprep should name that directory with an `.ica` extension or whether FSLeyes should not require that extension. (Or whether I and the researchers I support have misunderstood something!)

**Comment by dmd** [comment]
Cross-posted as https://github.com/poldracklab/fmriprep/issues/2077

**Comment by pauldmccarthy** [comment]
Hmm, I suppose there's no real need for the directory to end with `.ica` - this is just the convention when using the MELODIC GUI, and I was trying to use as much identifying information as possible (relevant code [here](https://git.fmrib.ox.ac.uk/fsl/fslpy/-/blob/4fb33a008c95c1de56eec2f0184d0e9f94c2467c/fsl/data/melodicanalysis.py#L65)).

But I don't really see the harm in removing this restriction, and identifying a directory based solely on its contents.

**Comment by pauldmccarthy** [comment]
This should be fixed in the latest versions of FSLeyes/fslpy - feel free to re-open if you are still having trouble.
