### ISSUE TITLE
Fixed error: drawing not working for 4D data

### ISSUE THREAD

**Issue by Symork** [pauldmccarthy/fsleyes#49]
Hi,

I would like to report an issue that I succeeded to fix.

The selection cursor didn't appear when I use the edit mode on 4D NIFTI data and I got an error when I tried to draw, select an area.

![image](https://user-images.githubusercontent.com/62758207/80699993-44820a80-8add-11ea-9a80-a31eb7edf92c.png)

This error was due to Blocksize variable in the orthoeditprofile. Indeed, at the line 1116, Blocksize is scaled on minimum voxel dimensions. In 4D, time dimension was considered and caused the error. I fixed it by restricting minimum scaling only on 3D dimension:
blockSize = np.min(overlay.pixdim[:3]) * blockSize

Hoping it helps you.

**Comment by Symork** [comment]
In orthoeditprofile script , at line 1116 in _drawCursorAnnotation function and at 1254 in __applySelection() function , the same rectification has to be done :
blockSize = np.min(overlay.pixdim[:3]) * blockSize

**Comment by pauldmccarthy** [comment]
Thanks again for the error report and the fix - I'll include this in the next version (although have limited time for FSLeyes development at the moment, so am not sure when that will be).

**Comment by pauldmccarthy** [comment]
This fix has been included in the most recent version of FSLeyes. Feel free to re-open if you come across any more problems
