### ISSUE TITLE
Bug in plotting slice coordinates? 

### ISSUE THREAD

**Issue by jnecus** [pauldmccarthy/fsleyes#5]
Hello,

I recently opened an issue on the nilearn package github ( see [here](https://github.com/nilearn/nilearn/issues/1740) ) whereby I noticed a discrepancy between how fsleyes and nilearn display images. I will copy and paste the main points below, but please see the issue link above for a full timeline.

1. The image below shows how fsleyes and mricron display a T1 image differently to nilearn. I have highlighted where the coordinates are displayed on mricron and fsleyes in red, and have highlighted the discrepancy in anatomical location in blue (it is most easily seen in the ventricles).  

![t1](https://user-images.githubusercontent.com/18306309/46289415-f44d6a00-c580-11e8-9ee0-476d3ddffc1d.png)

2. @bthirion has suggested that the cause of this is due to:

> FSLeyes does not take into account properly the information contained in the affine transformation in the image. This is seen when the affine is not a pure translation + rescaling, but also contains some rotation part.

see [previous issue](https://github.com/nilearn/nilearn/issues/1740) for an explanation of why this may be the case.

Any thoughts?

**Comment by pauldmccarthy** [comment]
Hi @jnecus, I don't think this is an issue in either FSLeyes or nilearn. It looks to me like nilearn is displaying the image after transforming the image by its affine transformation, and FSLeyes isn't. 

FSLeyes will, by default, display the image in a scaled voxel coordinate system - only the scalings are applied (and possibly a L/R flip), but not the translations or rotations. It looks like mricron behaves the same as FSLeyes, but nilearn defaults to applying the full affine.

You can tell FSLeyes to apply the affine by setting the *Display space* to *world* - this option can be found in the view settings panel (the spanner icon on the second toolbar). 

More information on the different spaces used by FSLeyes can be found [here](https://users.fmrib.ox.ac.uk/~paulmc/fsleyes/userdoc/latest/display_space.html) - I hope this clears things up!

**Comment by jnecus** [comment]
@pauldmccarthy Thank you for this explanation.

>You can tell FSLeyes to apply the affine by setting the Display space to world - this option can be found in the view settings panel (the spanner icon on the second toolbar).


By doing so this introduces line artefacts into the images as seen below (see axial frontal cortex for most clear example). Is this expected?

![t12](https://user-images.githubusercontent.com/18306309/46291488-8c9a1d80-c586-11e8-94e9-80bacb83eb4e.png)

**Comment by pauldmccarthy** [comment]
Hey @jnecus, yep, that is because the image is now being displayed obliquely to the display - the lines are slice boundaries. You can avoid them by opening the overlay display panel (the gear icon), and changing the *Interpolation* from *nearest neighbour* to *linear* or *spline*.

**Comment by jnecus** [comment]
@pauldmccarthy makes sense I think. So by specifying real world planes (-3,-5,30) we are forcing it to display in an angle oblique to how it was acquired. I will re-read the link that you posted above. Thank you very much for your time and help!

**Comment by neurolabusc** [comment]
By the way, with MRIcron you can also choose whether the image is resliced or not. If you go to the preferences, you can choose whether the image is displayed as saved to disk, rotated to the nearest orthogonal or resliced. This is a feature of these tools, as regions of interest need to be drawn with a one-to-one correspondence of voxels. Therefore, it is nice to control interpolation. We typically show final results on normalized brains, that are resliced to standard space where these issues vanish.
