### ISSUE TITLE
fsleyes does not quit: process remains and splash remains open/hidden

### ISSUE THREAD

**Issue by CGSchwarzMayo** [pauldmccarthy/fsleyes#50]
I have a brand new dev environment in centos7, running straight from git head with:

```
pipenv shell
pip install --only-binary wxpython -f https://extras.wxpython.org/wxPython4/extras/linux/gtk2/centos-7/ wxpython
git clone https://github.com/pauldmccarthy/fsleyes.git fsleyes
cd fsleyes
pip install -e .
```

When I run fsleyes in this environment, it does not quit after closing the  main dialog or FSLEyes | close from the menu. The process remains running until control-c or kill. The splash screen also remains open in the taskbar ("Untitled window", but hidden and does not reappear if clicked in the taskbar) the whole time the program is running, and does close until control-c or kill.

onFrameDestroy is called, but it never gets to shutdown() after app.MainLoop().

I do not have these behaviors when I run the version installed with fsl-6.0.3

If it matters, I'm running over x2go. 

If you can't replicate but have suggestions for code changes, I'm happy to test them. Thanks!

**Comment by CGSchwarzMayo** [comment]
Maybe relevant: when I run fsleyes_unfiltered, this warning appears in the console after closing the main window:

```
Gdk-WARNING **: 16:07:47.541: gdkdrawable-x11.c:952 drawable is not a pixmap or window
```

The warning occurs before onFrameDestroy() is called.

**Comment by pauldmccarthy** [comment]
Hi @CGSchwarzMayo, can you confirm the commit hash that you're running? I made some changes in the most recent version (merged into master on 8th June) which should help to avoid this issue. I might have done something wrong though.

**Comment by CGSchwarzMayo** [comment]
I'm on hash 50564023d45b032aae6bd8b44813c52ea633d0ad dated 8th June. This looks to still be HEAD,

**Comment by pauldmccarthy** [comment]
Ok, in that case I have probably broken something - I'll try and make some FSLeyes time at the end of this week, or possibly next, to investigate.

**Comment by pauldmccarthy** [comment]
Hi @CGSchwarzMayo, I've just pushed a change which hopefully resolves this - mind testing the latest code on master?

**Comment by CGSchwarzMayo** [comment]
Paul, I confirmed that your fix was successful. Thanks!
