### ISSUE TITLE
fontWeight is too light in some environments

### ISSUE THREAD

**Issue by CGSchwarzMayo** [pauldmccarthy/fsleyes#51]
In at least some environments, i.e. mine (Centos 7), OS-level font smoothing makes many UI fonts very difficult to read. Black text is smoothed to a point where it becomes medium-gray, which on the light-gray UI background becomes low-contrast.

I emailed you about this years ago thinking it was a font color issue and you pointed me to OS-level theme settings. I dug around the OS theme settings and I confirmed that the font is actually black but only looks gray due to the font smoothing. Then I dug around the fsleyes source for anything to do with font, and I found that frame.py has `font.SetWeight(wx.FONTWEIGHT_LIGHT)`. Changing this to `font.SetWeight(wx.FONTWEIGHT_NORMAL)` makes a world of difference to my eyes and suddenly I can use fsleyes without eye strain. I opened up a lot of forms and don't see any text cutting off that used to fit.

Light (current setting):
![fontWeight_light](https://user-images.githubusercontent.com/38332171/84697771-59dbb880-af14-11ea-8d63-1b8b24c11ffb.png)
Normal:
![fontWeight_normal](https://user-images.githubusercontent.com/38332171/84697785-5ea06c80-af14-11ea-9ee2-7b78a9685d79.png)

I see a few possible approaches:
1) Change the hard-coded setting to _NORMAL. 
2) Check some OS/environment settings (linux? centos?) and use _NORMAL only in that case
3) Leave the default alone and add a user-configurable option like --fontSize at the command line
4) Leave the default alone and add user-configurable font size/weight options through the config UI, which are saved in preferences.

Would you support any of these approaches? I could happily make a PR for any of 1-3; 4 might be more of a challenge but I'd be willing to try.

**Comment by pauldmccarthy** [comment]
Hi @CGSchwarzMayo, changing the font weight to `_NORMAL` doesn't have any effect on my system, but I don't see any problem with making that the default. I think the original choice of using `_LIGHT` was completely arbitrary anyway. So I'll change the default for the next release.

**Comment by CGSchwarzMayo** [comment]
Okay, great, thanks! Let me know if you want a PR; otherwise it sounds to me like you plan to do it without a PR.

**Comment by CGSchwarzMayo** [comment]
This was changed in 5f16e9f78121ab817f760a73fe63ac0f31575e58 and I confirmed that the expected result occurred. This is very much easier on the eyes. Thank you!
