### ISSUE TITLE
Some NIfTI images won't load with the new version of indexed_gzip

### ISSUE THREAD

**Issue by Stoyan-I-A** [pauldmccarthy/fsleyes#55]
This is a 2D NIfTI image:
[image_issue.nii.gz](https://github.com/pauldmccarthy/fsleyes/files/4832609/image_issue.nii.gz)

This image can be opened with no problem on FSLeyes when using indexed_gzip version 1.2.0

However, when using indexed_gzip version 1.3.0, this error shows up when trying to load this image:
```
An error occurred loading the image /home/stoyan/Desktop/image_issue.nii.gz

Details: Index must be completely built in order to seek from SEEK_END
```

**Comment by pauldmccarthy** [comment]
Closing this issue, as it is being addressed at pauldmccarthy/indexed_gzip#38, pauldmccarthy/indexed_gzip#39
