### ISSUE TITLE
Display Issues in FSLeyes

### ISSUE THREAD

**Issue by CarolineBao** [pauldmccarthy/fsleyes#56]
I'm having issues with displaying some NIfTI files properly in FSLeyes and am wondering if there's an issue with my files, FSLeyes, or my installation. Some of my files are properly centered but others aren't (I've linked two examples below). I'm seeing the same display when installing with pip, conda-forge, and installing FSLeyes as a part of the FSL (6.0.3) package (https://fsl.fmrib.ox.ac.uk/fsldownloads_registration/download/fsl=8,o_s=20,d_type=release/).  

I tested a file that wasn't displaying properly in FSLeyes in MRIcroGL, another viewer, and saw that it displayed properly there.

I've included images of what's displayed for MRIcro GL, installing FSLeyes with conda-forge, and installing FSLeyes with the FSL package below (the crosshairs are different in the latter 2 but the display matches when centered). A file I'm having issues with is (https://drive.google.com/file/d/1g6JTgW1Q5Lc0j31g1YwGq3M4_pViSI8z/view?usp=sharing) and an example file that's displaying fine is (https://drive.google.com/file/d/1w9uGKirzwIKwNL6DF8-N2MOQt2dE_M48/view?usp=sharing). Thank you!

MRIcroGL display:
<img width="1440" alt="Screen Shot 2020-06-29 at 10 48 52 AM" src="https://user-images.githubusercontent.com/37222366/86038987-a801b900-b9f6-11ea-9594-509c5c5302d5.png">

FSLeyes installed using conda-forge:
`conda install -c conda-forge fsleyes`
<img width="1440" alt="Screen Shot 2020-06-29 at 10 49 16 AM" src="https://user-images.githubusercontent.com/37222366/86038990-a89a4f80-b9f6-11ea-9b6c-d64110c252be.png">

FSLeyes installed as a part of the FSL (6.0.3) package:
<img width="1440" alt="Screen Shot 2020-06-29 at 11 23 00 AM" src="https://user-images.githubusercontent.com/37222366/86041877-34ae7600-b9fb-11ea-897a-b0c16fb35c00.png">

**Comment by pauldmccarthy** [comment]
Hi @CarolineBao, it looks like these two images are not aligned in the world coordinate system, which is defined by the voxel-to-world affine (a.k.a. qform/sform) in the NIFTI metadata. If you reset the pan/zoomsettings using the magnifying class button on the second toolbar, you should see this (I've only included the coronal/sagittal planes in this screenshot):

![screenshot](https://user-images.githubusercontent.com/236128/86098826-911e9d80-baae-11ea-9c69-182703980ddc.png)

Your `abi_40micron_average` image has voxel-to-world affine:

```
0.04 0    0    0 
0    0.04 0    0 
0    0    0.04 0 
0    0    0    1 
```

and `dsurqec_40micron.nii` has:

```
0.04 0    0    -6.27 
0    0.04 0    -10.6 
0    0    0.04 -7.8 
0    0    0     1
```

If you open each image individually in FSLeyes, they should both display correctly. But when you load multiple images into FSLeyes, it will use the voxel to world affines of each image to project them all into the same coordinate system. In the most recent version of FSLeyes a warning will be displayed in the location panel when you are viewing images which are not aligned in the world coordinate system.

Are these images from the same individual and scanning session? Are they supposed to be aligned? You may need to talk to your scanner operator, or have a look at how they were converted from DICOM to NIFTI - for the conversion I would recommend using the latest version of [dcm2niix](https://github.com/rordenlab/dcm2niix/).

**Comment by CarolineBao** [comment]
Got it, thank you for the help! The images are loaded from different MRI templates so I don't think the world coordinate system alignment is an issue.
