### ISSUE TITLE
Plotting  mesh figures with configurable camera angle from the CLI or via Python

### ISSUE THREAD

**Issue by TheChymera** [pauldmccarthy/fsleyes#6]
Can FSLEyes (or perhaps even one of its dependencies) create plots (2D vector or raster graphic) of 3D views of meshes via Bash or Python bindings?

I am asking because I would like to produce graphics for my publications in a fully reproducible fashion (fee of manual interaction, and unambiguously specified via code).

**Comment by pauldmccarthy** [comment]
Yes - you can use `fsleyes render` to perform off-screen rendering of volume/mesh overlays. An overview of the command-line interface can be found [here](https://users.fmrib.ox.ac.uk/~paulmc/fsleyes/userdoc/latest/command_line.html). If you are on a headless machine, you will need to use something like `xvfb-run` for this to work.

There is also a Python API (overview [here](https://users.fmrib.ox.ac.uk/~paulmc/fsleyes/userdoc/latest/fsleyes_notebook.html) - you can write a script against this API, and then run it from the command line via the `--runscript` flag.
