### ISSUE TITLE
[Question] Displaying text on an overlay

### ISSUE THREAD

**Issue by Stoyan-I-A** [pauldmccarthy/fsleyes#60]
Is there a feature that allows a user to display text on top of an overlay? (Ideally at a specific voxel coordinate)

Something like this:
![example_text_label](https://user-images.githubusercontent.com/43790661/89469659-e9009200-d747-11ea-86bf-f5a51b20f601.png)

I couldn't find a feature like this in the documentation, but I am asking just in case there is one.

**Comment by pauldmccarthy** [comment]
No, there is not currently any UI control for overlaying text or other annotations, althought it has been on the TODO list for quite some time.

In the meantime you can add annotations programmatically via the [`fsleyes.gl.annotations` module](https://users.fmrib.ox.ac.uk/~paulmc/fsleyes/apidoc/latest/fsleyes.gl.annotations.html), although functionality is somewhat limited, e.g.:

```python
ortho = frame.viewPanels[0]
xcanvas = ortho.getXCanvas()
xannot = xcanvas.getAnnotations()
xannot.text('howdy', 0.5, 0.5, halign='centre', valign='centre', colour=(255, 0, 0), fontSize=96, hold=True)
```

![screenshot](https://user-images.githubusercontent.com/236128/89506934-c01de280-d7c3-11ea-9749-d30c55a6796e.png)

**Comment by Stoyan-I-A** [comment]
All right, thanks for the reply.

**Comment by Stoyan-I-A** [comment]
Thanks for the update! I might try these.
