### ISSUE TITLE
How can I change the overlay name from python/jupyter?

### ISSUE THREAD

**Issue by jdoepfert** [pauldmccarthy/fsleyes#65]
I want to change the name `mask` in the overlay list:
![image](https://user-images.githubusercontent.com/7914340/102902604-8813f500-446f-11eb-9326-0e6a5eb8ba72.png)
I tried
```
img = load(img_path)
img.name ="new_name"
```
But that did not change the names in the fsleyes viewer, however it did change the name of `img`:

```
>> img
Image(new_name, /path/to/img.nii.gz)
```

Any help on how to do this would be appreciated :)

**Comment by pauldmccarthy** [comment]
Hi @jdoepfert, all display properties of an overlay are available through a pair of objects - the `Display`, and the `DisplayOpts`. The `Display` object contains properties common to all overlays (e.g. `name`, `alpha`, etc), and the `DisplayOpts` object contains properties specific to the overlay type (e.g. `volume`, `mask`, etc). You can access both via the `DisplayContext` object, which is available in the jupyter notebook environment as `displayCtx`:

```
display      = displayCtx.getDisplay(img)
opts         = displayCtx.getOpts(img)
display.name = 'new name'
```

More information here:
 - https://users.fmrib.ox.ac.uk/~paulmc/fsleyes/userdoc/latest/fsleyes_notebook.html#display-settings
 - https://users.fmrib.ox.ac.uk/~paulmc/fsleyes/apidoc/latest/fsleyes.displaycontext.html

**Comment by jdoepfert** [comment]
thx a lot 👍
