### ISSUE TITLE
Upgrade dcm2niix dependency version

### ISSUE THREAD

**Issue by ahill187** [pauldmccarthy/fsleyes#69]
## Issue

Currently, `fsleyes` requires `dcm2niix`=1.0.20181114. However, this is two years old, and has become outdated. It would be ideal if `fsleyes` could change the dependency to `dcm2niix`=1.0.20201224 (the current version).

https://anaconda.org/conda-forge/dcm2niix

Not sure if it's related to this: https://git.fmrib.ox.ac.uk/fsl/fsleyes/build/-/blob/master/.ci/install_dcm2niix.sh

**Comment by pauldmccarthy** [comment]
No problem - I'm aiming to release a new version of FSLeyes within the next couple of weeks, so will update the conda recipe then.

**Comment by ahill187** [comment]
Perfect thanks so much!!

**Comment by gaspardcereza** [comment]
Hi @pauldmccarthy, do you still plan to release a new version soon ? We have to deal with some "hacky" tricks to make fsleyes compatible with our default virtual environment so we're all looking forward to the update ! 😄 
Thanks

**Comment by pauldmccarthy** [comment]
@gaspardcereza Sorry - yes - I perpetually under-estimate the amount of free time I have. Still aiming for a new release in the next couple of weeks. In the meantime. I've updated the conda recipe, so you should be able to re-install FSLeyes 0.34.2 alongside a newer version of dcm2niix.

**Comment by gaspardcereza** [comment]
Awesome ! Thank you very much !

**Comment by pauldmccarthy** [comment]
This should be fixed as of the latest FSLeyes (1.0.3), please let me know if you're still having trouble
