### ISSUE TITLE
Feature request: Edit feature like Mango

### ISSUE THREAD

**Issue by dkp** [pauldmccarthy/fsleyes#71]
In Mango, there is a very useful edit tool:
If you drag from outside an roi it erases.  If you drag from inside an roi, it paints.
This is useful because, in lesion mapping, one often has to paint and erase over and over again in quick succession.
If there is any possibility you could add this tool it would be very useful!

**Comment by pauldmccarthy** [comment]
In FSLeyes, when you're in "draw" mode, you can use a left mouse click to paint, or right mouse click to erase.  Similarly, when in "select" mode, you can use left mouse click to add to the selection, and right mouse click to remove from the selection.

**Comment by dkp** [comment]
Wonderful!! Thanks so much.  Sorry I missed that.
