### ISSUE TITLE
ImportError: ('Unable to load openGL library'), MacOS Catalina/BigSur

### ISSUE THREAD

**Issue by PyMarc2** [pauldmccarthy/fsleyes#73]
For those with a recent macOS version (Catalina/BigSur), the directory in which OpenGL is installed has changed and this might cause some issues. If you have installed XCode, but still see the following error after launch:

`ImportError: ('Unable to load openGL library', 'dlopen(OpenGL, 10): image not found', 'OpenGL', None)`

I found the source of the problem. This is caused by a problem in `cpython`. They have corrected the issue in a bugfix they did on February 12th 2021. If you have a python version that has been installed before the fix, you might have the same problem. It is related to this [issue](https://github.com/PixarAnimationStudios/USD/issues/1372). And the `cpython` thread for the bug fix is [here](https://github.com/python/cpython/pull/21241). 

`pip install --upgrade cpython`
`pip install --update cpython`

This fixed the issue for me. Created this for the community in case they have the same issue.

**Comment by pauldmccarthy** [comment]
I'm afraid that:

```
pip install --upgrade cpython
pip install --update cpython
```

is not doing what you think it is doing. So you must have done something else to resolve the issue.

The `Unable to load openGL library` issue concerns the CPython interpreter, which cannot be installed/updated with `pip`, but rather is provided by your OS, `conda`, or the official installers from https://www.python.org/. The [`cpython` pypi package](https://pypi.org/project/cPython/) is related to [this project](https://github.com/JxiaoC/cPython), which has nothing to do with the present issue.

The latest version of FSLeyes on conda-forge has ca work-around, so if you updated FSLeyes with `conda`, this will have resolved the problem.

**Comment by PyMarc2** [comment]
I swear, this is the only thing that I have done. I installed fsleye with pip.

**Comment by dmd** [comment]
We're getting this error on a fresh install of FSL using the regular FSL installer. Is there a workaround for that?
