### ISSUE TITLE
Add from file empty

### ISSUE THREAD

**Issue by proflagosta** [pauldmccarthy/fsleyes#74]
Hello, I'm trying to add files with a '.nii.gz' extension, but I can't find a single item. I tried to add a path to where the files are, but it pops up as empty, I don't think I really added much of anything. I'm a newbie to this, so i really have no idea on whats going on? When i open the add a file overlay, it says the file I'm at is "X". Now, I have no clue where that file is and I've tried to find answers on the internet and honestly, couldn't find any. 

![Screenshot (3)](https://user-images.githubusercontent.com/82324823/114308624-7c127880-9adc-11eb-8182-99c6e714f9b0.png)

The file I added would be the "tese" one. The above image shows it from the FSL perspective
![Screenshot (4)](https://user-images.githubusercontent.com/82324823/114308714-acf2ad80-9adc-11eb-9013-8c37a972ba6b.png)

This is what is inside

**Comment by pauldmccarthy** [comment]
You should be able to access files on your Windows Desktop from the WSL environment by navigating to `/mnt/c/Users/franc/Desktop/.../`

**Comment by proflagosta** [comment]
Dear Paul, 

Thank you so very much! I'm sorry you had to be as specific as that, but I really do appreciate it :)
