### ISSUE TITLE
FSLDIR required?

### ISSUE THREAD

**Issue by TheChymera** [pauldmccarthy/fsleyes#8]
On startup fsleyes complains about FSLDIR not being set. Why is this required for this package? If it isn't really, what's the best way to disable this check?

Btw, thank you for all of your help. I realize it's a bit much, but I'm really trying to package your software properly for my distribution.

**Comment by pauldmccarthy** [comment]
FSLeyes will work fine without the `$FSLDIR` - a handful of things (e.g. the atlas panel, the robustfov button in the crop tool, etc) will be disabled if FSL is not present. The easiest way to disable the check is via the `--skipfslcheck` command line flag. Alternately, you could patch `fsleyes/main.py`- there is a function near the bottom called `fslDirWarning` which controls the check.
