### ISSUE TITLE
Use Jinja2 version 3.x

### ISSUE THREAD

**Issue by sanjayankur31** [pauldmccarthy/fsleyes#82]
Hello,

The latest version of Jinja2 is now 3.x, but fsleyes requires 2.x. Would it be possible to use the new Jinja2 release please?

I looked at the changelog and it seems to be mostly bugfixes:

https://jinja.palletsprojects.com/en/3.0.x/changes/

Cheers,

**Comment by pauldmccarthy** [comment]
@sanjayankur31 Sorry, I missed this when you posted it - I'll relax the pinning in the next release (probably next week).
