### ISSUE TITLE
Depth Picking

### ISSUE THREAD

**Issue by neurolabusc** [pauldmccarthy/fsleyes#83]
The volume rendering of FSLeyes already write to `gl_FragDepth` to ensure that the cross-hairs are occluded when they are behind the rendered surface.

As a enhancement request, it would be very easy to make the rendered crosshairs interactive, where clicking on the rendered image moves the crosshairs to the selected location on the surface. This is illustrated in with [MRIcroGL v1.2.20210816](https://github.com/rordenlab/MRIcroGL/releases/tag/v1.2.20210816). 

All you have to do is 
 1. use `glReadPixels` to sample the GL_DEPTH_COMPONENT at the location of a mouse click.
 2. [unproject](http://nehe.gamedev.net/article/using_gluunproject/16013/) the mouse/depth position from screen space to object space.

I describe the method and formula [here](https://github.com/rordenlab/MRIcroGL/tree/master/DepthPicking). This will work best for raw MRI scans if the images remove [haze](https://github.com/rordenlab/MRIcroGL/tree/master/Haze).

**Comment by pauldmccarthy** [comment]
Hi @neurolabusc aah, that's a good idea - I had already implemented depth picking for surfaces, but never thought to do so for volumes. 

The way that I tend to use FSLeyes 3D is to use the clipping range to hide voxels outside with low intensity. With that workflow I could get away without having to implement haze removal. But it does sound like a nice idea - what harm could one more display settings checkbox do? :) Thanks for the insight and the links.

**Comment by pauldmccarthy** [comment]
@neurolabusc I came up with a lazy alternative to haze removal. In FSLeyes, the image data is presented to the fragment shader as being normalised to the range `[0, 1]` with respect to the current display range (i.e. voxels corresponding to the minimum colour are set to 0, and those corresponding to the maximum colour set to 1). 

So I figured that a simple approach might be to set the depth from the first voxel sampled along each ray which is above a fixed threshold. Below I am taking the first voxel with a value above 0.1. Do you see any issues with this approach?

https://user-images.githubusercontent.com/236128/136036422-0b534bdb-39e1-4baa-bb3e-306e2f6e96d0.mp4

**Comment by neurolabusc** [comment]
@pauldmccarthy I think this is a good approach. You can also extend this for the visualization, not just the depth picking.

Having the color transfer texture contain both color (red, green, blue) and opacity (alpha) is also a nice way to provide the user control over this feature. The images below show how MRIcroGL allows the user to interactively adjust the alpha (vertical axis) with respect to image intensity (horizontal axis). Note with the T1 scan, interactively adjusting the alpha can allow the user to remove haze. The CT scan shows the notion that we do not always want opacity to increase with increasing voxel intensity: in this example mid-range blood and very bright bone are made opaque, but intermediate intensities are translucent.

![editor1](https://user-images.githubusercontent.com/8930807/136040268-2f065834-5d57-48c9-aaa8-3bf94b1ac72a.jpg)

![editor2](https://user-images.githubusercontent.com/8930807/136040304-f0cdaabb-577b-40a8-8951-5c4fb6b807f8.jpg)

![editor2](https://user-images.githubusercontent.com/8930807/136040285-87fc404f-00c0-4531-98fd-5769861bbd24.jpg)

![editor3](https://user-images.githubusercontent.com/8930807/136040325-a141d4d7-499f-4001-a4ae-56c04255e486.jpg)
