### ISSUE TITLE
Problem with FSLStats \ FSLEyes

### ISSUE THREAD

**Issue by Rokujo001** [pauldmccarthy/fsleyes#85]
Hi to all, 

I'm having a problem in the final step of TBSS protocol. I have 49 subjects in my analysis and after prestats and the voxelwise statistics, I was trying to extract the values to begin the statistical analysis. 
With FSLeyes everything is ok and there was no errors through all the steps.

Using  `fslstats -t all_FA_skeletonised.nii.gz -k . $path/mean_FA_skeleton_mask -M > ./mean_FA.txt`  results into an error: 

Image Exception : #63 :: No image files match: .
Image Exception : #22 :: Failed to read volume .
Error : No image files match: .
Failed to read volume .
Error : No image files match: .

I really can't understand it: I have only 49 subjects, so why the #63 image is considered? And Why the #22 failed only at this point? 

Is there some other method to extract the statistical values? 

Thanks in advance to all of you.

Filippo

**Comment by pauldmccarthy** [comment]
Hi @Rokujo001, this question is better suited for the [FSL Mailing List](https://www.jiscmail.ac.uk/cgi-bin/webadmin?A0=FSL) - you can subscribe here.

But it looks like you are using `fslstats` incorrectly - the `-k` option expects a mask image, but you are passing it `.` (a path to the current directory).

**Comment by Rokujo001** [comment]
Thank you, I'll ask it in the other section!
