### ISSUE TITLE
macos fsleyes 1.2 to 1.3 update osmesa error reappears

### ISSUE THREAD

**Issue by mrjeffstevenson3** [pauldmccarthy/fsleyes#90]
hi @pauldmccarthy, upgrade and/or fresh install of fsleyes 1.3 on macos has similar openGL error to issue 80 and 43. here is back trace. clean install attempted for python 3.8 and 3.9.

fsleyes
Traceback (most recent call last):
  File "/Users/mrjeffs/Software/anaconda2/envs/py38fsleyes_1/lib/python3.8/site-packages/PyOpenGL-3.1.5-py3.8.egg/OpenGL/platform/osmesa.py", line 22, in GL
    return ctypesloader.loadLibrary(
  File "/Users/mrjeffs/Software/anaconda2/envs/py38fsleyes_1/lib/python3.8/site-packages/PyOpenGL-3.1.5-py3.8.egg/OpenGL/platform/ctypesloader.py", line 36, in loadLibrary
    return _loadLibraryWindows(dllType, name, mode)
  File "/Users/mrjeffs/Software/anaconda2/envs/py38fsleyes_1/lib/python3.8/site-packages/PyOpenGL-3.1.5-py3.8.egg/OpenGL/platform/ctypesloader.py", line 89, in _loadLibraryWindows
    return dllType( name, mode )
  File "/Users/mrjeffs/Software/anaconda2/envs/py38fsleyes_1/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: ('dlopen(OSMesa, 10): image not found', 'OSMesa', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mrjeffs/Software/anaconda2/envs/py38fsleyes_1/bin/fsleyes", line 33, in <module>
    sys.exit(load_entry_point('fsleyes', 'gui_scripts', 'fsleyes')())
  File "/Users/mrjeffs/Software/fsleyes/fsleyes/filtermain.py", line 208, in main
    result = fm.main(args)
  File "/Users/mrjeffs/Software/fsleyes/fsleyes/main.py", line 243, in main
    fsleyes.initialise()
  File "/Users/mrjeffs/Software/fsleyes/fsleyes/__init__.py", line 243, in initialise
    import fsleyes.plugins as plugins
  File "/Users/mrjeffs/Software/fsleyes/fsleyes/plugins/__init__.py", line 196, in <module>
    import fsleyes.views.canvaspanel     as canvaspanel
  File "/Users/mrjeffs/Software/fsleyes/fsleyes/views/canvaspanel.py", line 20, in <module>
    from . import                    colourbarpanel
  File "/Users/mrjeffs/Software/fsleyes/fsleyes/views/colourbarpanel.py", line 15, in <module>
    import fsleyes.gl.wxglcolourbarcanvas as cbarcanvas
  File "/Users/mrjeffs/Software/fsleyes/fsleyes/gl/wxglcolourbarcanvas.py", line 17, in <module>
    import fsleyes.gl.colourbarcanvas as cbarcanvas
  File "/Users/mrjeffs/Software/fsleyes/fsleyes/gl/colourbarcanvas.py", line 21, in <module>
    import OpenGL.GL as gl
  File "/Users/mrjeffs/Software/anaconda2/envs/py38fsleyes_1/lib/python3.8/site-packages/PyOpenGL-3.1.5-py3.8.egg/OpenGL/GL/__init__.py", line 3, in <module>
    from OpenGL import error as _error
  File "/Users/mrjeffs/Software/anaconda2/envs/py38fsleyes_1/lib/python3.8/site-packages/PyOpenGL-3.1.5-py3.8.egg/OpenGL/error.py", line 12, in <module>
    from OpenGL import platform, _configflags
  File "/Users/mrjeffs/Software/anaconda2/envs/py38fsleyes_1/lib/python3.8/site-packages/PyOpenGL-3.1.5-py3.8.egg/OpenGL/platform/__init__.py", line 36, in <module>
    _load()
  File "/Users/mrjeffs/Software/anaconda2/envs/py38fsleyes_1/lib/python3.8/site-packages/PyOpenGL-3.1.5-py3.8.egg/OpenGL/platform/__init__.py", line 33, in _load
    plugin.install(globals())
  File "/Users/mrjeffs/Software/anaconda2/envs/py38fsleyes_1/lib/python3.8/site-packages/PyOpenGL-3.1.5-py3.8.egg/OpenGL/platform/baseplatform.py", line 97, in install
    namespace[ name ] = getattr(self,name,None)
  File "/Users/mrjeffs/Software/anaconda2/envs/py38fsleyes_1/lib/python3.8/site-packages/PyOpenGL-3.1.5-py3.8.egg/OpenGL/platform/baseplatform.py", line 15, in __get__
    value = self.fget( obj )
  File "/Users/mrjeffs/Software/anaconda2/envs/py38fsleyes_1/lib/python3.8/site-packages/PyOpenGL-3.1.5-py3.8.egg/OpenGL/platform/osmesa.py", line 66, in GetCurrentContext
    function = self.OSMesa.OSMesaGetCurrentContext
  File "/Users/mrjeffs/Software/anaconda2/envs/py38fsleyes_1/lib/python3.8/site-packages/PyOpenGL-3.1.5-py3.8.egg/OpenGL/platform/baseplatform.py", line 15, in __get__
    value = self.fget( obj )
  File "/Users/mrjeffs/Software/anaconda2/envs/py38fsleyes_1/lib/python3.8/site-packages/PyOpenGL-3.1.5-py3.8.egg/OpenGL/platform/osmesa.py", line 60, in OSMesa
    def OSMesa( self ): return self.GL
  File "/Users/mrjeffs/Software/anaconda2/envs/py38fsleyes_1/lib/python3.8/site-packages/PyOpenGL-3.1.5-py3.8.egg/OpenGL/platform/baseplatform.py", line 15, in __get__
    value = self.fget( obj )
  File "/Users/mrjeffs/Software/anaconda2/envs/py38fsleyes_1/lib/python3.8/site-packages/PyOpenGL-3.1.5-py3.8.egg/OpenGL/platform/osmesa.py", line 28, in GL
    raise ImportError("Unable to load OpenGL library", *err.args)
ImportError: ('Unable to load OpenGL library', 'dlopen(OSMesa, 10): image not found', 'OSMesa', None)

**Comment by pauldmccarthy** [comment]
Hi @mrjeffstevenson3, can you paste the output of `cat $(which fsleyes)`? There is a chance that the FSLeyes entry point has been created incorrectly, with the effect that it is being executed with the wrong python executable. This is an issue with conda/python.app that I have not gotten around to diagnosing.

**Comment by pauldmccarthy** [comment]
Also, can I ask what version of conda you have installed (`conda info`)? Perhaps you have an older version of conda which is susceptible to this issue..

**Comment by mrjeffstevenson3** [comment]
(py39fsleyes_1) $: conda activate py38fsleyes_1
(py38fsleyes_1)  $: which fsleyes
/Users/mrjeffs/Software/anaconda2/envs/py38fsleyes_1/bin/fsleyes

and per your request:

(py38fsleyes_1)  $: cat $(which fsleyes)
#!/Users/mrjeffs/Software/anaconda2/envs/py38fsleyes_1/bin/python
# EASY-INSTALL-ENTRY-SCRIPT: 'fsleyes','gui_scripts','fsleyes'
import re
import sys

# for compatibility with easy_install; see #2198
__requires__ = 'fsleyes'

try:
    from importlib.metadata import distribution
except ImportError:
    try:
        from importlib_metadata import distribution
    except ImportError:
        from pkg_resources import load_entry_point


def importlib_load_entry_point(spec, group, name):
    dist_name, _, _ = spec.partition('==')
    matches = (
        entry_point
        for entry_point in distribution(dist_name).entry_points
        if entry_point.group == group and entry_point.name == name
    )
    return next(matches).load()


globals().setdefault('load_entry_point', importlib_load_entry_point)


if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(load_entry_point('fsleyes', 'gui_scripts', 'fsleyes')())

and then for conda:
(py38fsleyes_1) $: conda info

     active environment : py38fsleyes_1
    active env location : /Users/mrjeffs/Software/anaconda2/envs/py38fsleyes_1
            shell level : 3
       user config file : /Users/mrjeffs/.condarc
 populated config files : /Users/mrjeffs/.condarc
          conda version : 4.8.4
    conda-build version : 3.17.8
         python version : 2.7.16.final.0
       virtual packages : __osx=10.14.6
       base environment : /Users/mrjeffs/Software/anaconda2  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/dfroger/osx-64
                          https://conda.anaconda.org/dfroger/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/mrjeffs/Software/anaconda2/pkgs
                          /Users/mrjeffs/.conda/pkgs
       envs directories : /Users/mrjeffs/Software/anaconda2/envs
                          /Users/mrjeffs/.conda/envs
               platform : osx-64
             user-agent : conda/4.8.4 requests/2.21.0 CPython/2.7.16 Darwin/18.7.0 OSX/10.14.6
                UID:GID : 501:20
             netrc file : None
           offline mode : False

**Comment by pauldmccarthy** [comment]
Would you be able to open `/Users/mrjeffs/Software/anaconda2/envs/py38fsleyes_1/bin/fsleyes` in a text editor, and change the first line from;

`#!/Users/mrjeffs/Software/anaconda2/envs/py38fsleyes_1/bin/python`

to:

`#!/Users/mrjeffs/Software/anaconda2/envs/py38fsleyes_1/bin/pythonw`

and see if that fixes things?

**Comment by mrjeffstevenson3** [comment]
hi @pauldmccarthy, sorry no love:

(py38fsleyes_1) ~/Software $: which python
/Users/mrjeffs/Software/anaconda2/envs/py38fsleyes_1/bin/python
(py38fsleyes_1) ~/Software $: which pythonw
/Users/mrjeffs/Software/anaconda2/envs/py38fsleyes_1/bin/pythonw
(py38fsleyes_1) ~/Software $: fsleyes
Version: ImageMagick 7.1.0-7 Q16-HDRI x86_64 2021-09-12 https://imagemagick.org
Copyright: (C) 1999-2021 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules OpenMP(3.1)
Delegates (built-in): bzlib fontconfig freetype gslib heic jng jp2 jpeg lcms lqr ltdl lzma openexr png ps tiff webp xml zlib
Compiler: gcc (4.2)
Usage: import [options ...] [ file ]

Image Settings:
  -adjoin              join images into a single multi-image file
  -border              include window border in the output image
  -channel type        apply option to select image channels
  -colorspace type     alternate image colorspace
  -comment string      annotate image with comment
  -compress type       type of pixel compression when writing the image
  -define format:option
                       define one or more image format options
  -density geometry    horizontal and vertical density of the image
  -depth value         image depth
  -descend             obtain image by descending window hierarchy
  -display server      X server to contact
  -dispose method      layer disposal method
  -dither method       apply error diffusion to image
  -delay value         display the next image after pausing
  -encipher filename   convert plain pixels to cipher pixels
  -endian type         endianness (MSB or LSB) of the image
  -encoding type       text encoding type
  -filter type         use this filter when resizing an image
  -format "string"     output formatted image characteristics
  -frame               include window manager frame
  -gravity direction   which direction to gravitate towards
  -identify            identify the format and characteristics of the image
  -interlace type      None, Line, Plane, or Partition
  -interpolate method  pixel color interpolation method
  -label string        assign a label to an image
  -limit type value    Area, Disk, Map, or Memory resource limit
  -monitor             monitor progress
  -page geometry       size and location of an image canvas
  -pause seconds       seconds delay between snapshots
  -pointsize value     font point size
  -quality value       JPEG/MIFF/PNG compression level
  -quiet               suppress all warning messages
  -regard-warnings     pay attention to warning messages
  -repage geometry     size and location of an image canvas
  -respect-parentheses settings remain in effect until parenthesis boundary
  -sampling-factor geometry
                       horizontal and vertical sampling factor
  -scene value         image scene number
  -screen              select image from root window
  -seed value          seed a new sequence of pseudo-random numbers
  -set property value  set an image property
  -silent              operate silently, i.e. don't ring any bells
  -snaps value         number of screen snapshots
  -support factor      resize support: > 1.0 is blurry, < 1.0 is sharp
  -synchronize         synchronize image to storage device
  -taint               declare the image as modified
  -transparent-color color
                       transparent color
  -treedepth value     color tree depth
  -verbose             print detailed information about the image
  -virtual-pixel method
                       Constant, Edge, Mirror, or Tile
  -window id           select window with this id or name
                       root selects whole screen

Image Operators:
  -annotate geometry text
                       annotate the image with text
  -colors value        preferred number of colors in the image
  -crop geometry       preferred size and location of the cropped image
  -encipher filename   convert plain pixels to cipher pixels
  -extent geometry     set the image size
  -geometry geometry   preferred size or location of the image
  -help                print program options
  -monochrome          transform image to black and white
  -negate              replace every pixel with its complementary color
  -quantize colorspace reduce colors in this colorspace
  -resize geometry     resize the image
  -rotate degrees      apply Paeth rotation to the image
  -strip               strip image of all profiles and comments
  -thumbnail geometry  create a thumbnail of the image
  -transparent color   make this color transparent within the image
  -trim                trim image edges
  -type type           image type

Miscellaneous Options:
  -debug events        display copious debugging information
  -help                print program options
  -list type           print a list of supported option arguments
  -log format          format of debugging information
  -version             print version information

By default, 'file' is written in the MIFF image format.  To
specify a particular image format, precede the filename with an image
format name and a colon (i.e. ps:image) or specify the image type as
the filename suffix (i.e. image.ps).  Specify 'file' as '-' for
standard input or output.
import: delegate library support not built-in '' (X11) @ error/import.c/ImportImageCommand/1297.
Version: ImageMagick 7.1.0-7 Q16-HDRI x86_64 2021-09-12 https://imagemagick.org
Copyright: (C) 1999-2021 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules OpenMP(3.1)
Delegates (built-in): bzlib fontconfig freetype gslib heic jng jp2 jpeg lcms lqr ltdl lzma openexr png ps tiff webp xml zlib
Compiler: gcc (4.2)
Usage: import [options ...] [ file ]

Image Settings:
  -adjoin              join images into a single multi-image file
  -border              include window border in the output image
  -channel type        apply option to select image channels
  -colorspace type     alternate image colorspace
  -comment string      annotate image with comment
  -compress type       type of pixel compression when writing the image
  -define format:option
                       define one or more image format options
  -density geometry    horizontal and vertical density of the image
  -depth value         image depth
  -descend             obtain image by descending window hierarchy
  -display server      X server to contact
  -dispose method      layer disposal method
  -dither method       apply error diffusion to image
  -delay value         display the next image after pausing
  -encipher filename   convert plain pixels to cipher pixels
  -endian type         endianness (MSB or LSB) of the image
  -encoding type       text encoding type
  -filter type         use this filter when resizing an image
  -format "string"     output formatted image characteristics
  -frame               include window manager frame
  -gravity direction   which direction to gravitate towards
  -identify            identify the format and characteristics of the image
  -interlace type      None, Line, Plane, or Partition
  -interpolate method  pixel color interpolation method
  -label string        assign a label to an image
  -limit type value    Area, Disk, Map, or Memory resource limit
  -monitor             monitor progress
  -page geometry       size and location of an image canvas
  -pause seconds       seconds delay between snapshots
  -pointsize value     font point size
  -quality value       JPEG/MIFF/PNG compression level
  -quiet               suppress all warning messages
  -regard-warnings     pay attention to warning messages
  -repage geometry     size and location of an image canvas
  -respect-parentheses settings remain in effect until parenthesis boundary
  -sampling-factor geometry
                       horizontal and vertical sampling factor
  -scene value         image scene number
  -screen              select image from root window
  -seed value          seed a new sequence of pseudo-random numbers
  -set property value  set an image property
  -silent              operate silently, i.e. don't ring any bells
  -snaps value         number of screen snapshots
  -support factor      resize support: > 1.0 is blurry, < 1.0 is sharp
  -synchronize         synchronize image to storage device
  -taint               declare the image as modified
  -transparent-color color
                       transparent color
  -treedepth value     color tree depth
  -verbose             print detailed information about the image
  -virtual-pixel method
                       Constant, Edge, Mirror, or Tile
  -window id           select window with this id or name
                       root selects whole screen

Image Operators:
  -annotate geometry text
                       annotate the image with text
  -colors value        preferred number of colors in the image
  -crop geometry       preferred size and location of the cropped image
  -encipher filename   convert plain pixels to cipher pixels
  -extent geometry     set the image size
  -geometry geometry   preferred size or location of the image
  -help                print program options
  -monochrome          transform image to black and white
  -negate              replace every pixel with its complementary color
  -quantize colorspace reduce colors in this colorspace
  -resize geometry     resize the image
  -rotate degrees      apply Paeth rotation to the image
  -strip               strip image of all profiles and comments
  -thumbnail geometry  create a thumbnail of the image
  -transparent color   make this color transparent within the image
  -trim                trim image edges
  -type type           image type

Miscellaneous Options:
  -debug events        display copious debugging information
  -help                print program options
  -list type           print a list of supported option arguments
  -log format          format of debugging information
  -version             print version information

By default, 'file' is written in the MIFF image format.  To
specify a particular image format, precede the filename with an image
format name and a colon (i.e. ps:image) or specify the image type as
the filename suffix (i.e. image.ps).  Specify 'file' as '-' for
standard input or output.
import: delegate library support not built-in '' (X11) @ error/import.c/ImportImageCommand/1297.
/Users/mrjeffs/Software/anaconda2/envs/py38fsleyes_1/bin/fsleyes: line 7: __requires__: command not found
/Users/mrjeffs/Software/anaconda2/envs/py38fsleyes_1/bin/fsleyes: line 9: try:: command not found
from: can't read /var/mail/importlib.metadata
/Users/mrjeffs/Software/anaconda2/envs/py38fsleyes_1/bin/fsleyes: line 11: except: command not found
/Users/mrjeffs/Software/anaconda2/envs/py38fsleyes_1/bin/fsleyes: line 12: try:: command not found
from: can't read /var/mail/importlib_metadata
/Users/mrjeffs/Software/anaconda2/envs/py38fsleyes_1/bin/fsleyes: line 14: except: command not found
from: can't read /var/mail/pkg_resources
/Users/mrjeffs/Software/anaconda2/envs/py38fsleyes_1/bin/fsleyes: line 18: syntax error near unexpected token `('
/Users/mrjeffs/Software/anaconda2/envs/py38fsleyes_1/bin/fsleyes: line 18: `def importlib_load_entry_point(spec, group, name):'

**Comment by pauldmccarthy** [comment]
How about changing it to`#!/Users/mrjeffs/Software/anaconda2/envs/py38fsleyes_1/bin/python.app` ?

I'm afraid I really don't know what is going on, and I am unable to reproduce it. Ultimately this is due to some kind of problem which has manifested itself in your [ana]conda installation. If you have the option of deleting / re-creating your base anaconda installation, and re-creating your child environment[s], that will probably resolve things.

I often see weird issues like this arising when software packages are installed into the base conda environment, rather than into child environments. This is nearly always a very bad idea, and I would recommend never changing anything in your base environment (with the sole exception of updating conda / conda-build, making sure to update from the same channel, i.e. `defaults` if you are using anaconda, or `conda-forge` if you are using miniforge).

**Comment by mrjeffstevenson3** [comment]
hi @pauldmccarthy I just installed fsleyes 1.3.3 and everything is back to working on MacOS. thanks for your and your team's hard work. Is it worth opening the can of worms that is apple abandoning openGL,
of which I believe this is a part? either way, consider this issue now closed.
