### ISSUE TITLE
wxPython 4.1.2

### ISSUE THREAD

**Issue by sanjayankur31** [pauldmccarthy/fsleyes#94]
Hiya,

The Fedora wxPython maintainer is thinking of updating wxPython to 4.1.2 when it's released. See:

https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/6Y6DDQFKEZZNVBR5OTTUPC4MXNE2D6OD/#YSY7VCWJB6GEBWDCIVC3NCBTZCQP3B4A

I haven't had the chance to build all our fsleyes related packages with their test wxPython-4.1.2 build  yet, but I'm hoping to do it this week. Have you had a chance to test with wxPython 4.1.2? Any issues that I should let the maintainer know about?

Cheers,

**Comment by pauldmccarthy** [comment]
Hi @sanjayankur31, I haven't tested against 4.1.2, but FSLeyes should work fine with 4.1.0 / 4.1.1, and it sounds like the concern is more about the move from 4.0.x to 4.1.x?

I don't see anything problematic in the provisional [4.1.2 changelog](https://github.com/wxWidgets/Phoenix/blob/master/CHANGES.rst), but I'll try and have a play over the next couple of weeks and get back to you if I find any problems.
