### ISSUE TITLE
display problem of coregistered images from AFNI

### ISSUE THREAD

**Issue by hitrp** [pauldmccarthy/fsleyes#95]
Hi,

We are trying to conduct probability tractography using FSL (6.0.5.1), so the seed and waypoint mask are warped from MNI space to native T1 space, this was done with AFNI (21.1.01) software, the qform and sform parameter were revised to Anat space with fsledithd command, they were well-registered in AFNI viewer, well, not registered when viewed in FSLeyes.

We have tried to set sform=qform, which didn't work, we found that they are not registered in reference/world coordinate display space but registered in scaled voxel display space, could you give some suggestions on this problem? is this a header problem or a compatibility problem between the two software?

Best wishes,
Peng

**Comment by pauldmccarthy** [comment]
Hi @hitrp, specifically what images are not registered when viewed in FSLeyes? What is the output of running `fslhd` on those images?

**Comment by hitrp** [comment]
Dear,&nbsp;


I am simply register MNI152 T1 template to subject T1 image (anat.nii), the result (mni2subj.nii) is well-registered with subject T1 in afni, but not in fsl, the output of fslhd is also attached.&nbsp;


Best wishes,
Peng


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "pauldmccarthy/fsleyes"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月26日(星期三) 晚上7:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [pauldmccarthy/fsleyes] display problem of coregistered images from AFNI (Issue #95)





 
Hi @hitrp, specifically what images are not registered when viewed in FSLeyes? What is the output of running fslhd on those images?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by pauldmccarthy** [comment]
Hi @hitrp, github has stripped any attachments that were part of your email - can you attach the output using the github issue interface instead?

**Comment by hitrp** [comment]
Sorry, the output of fslhd command are attached.
[anat.docx](https://github.com/pauldmccarthy/fsleyes/files/7942473/anat.docx)
[mni2subj.docx](https://github.com/pauldmccarthy/fsleyes/files/7942477/mni2subj.docx)

**Comment by hitrp** [comment]
by the way, we have tried to copy the sto_xyz_matrix of anat.nii to the result images (mni2subj.nii), it works, but we don't know whether it's reasonable.

**Comment by pauldmccarthy** [comment]
I'm not familiar with how AFNI tools work, but in the context of FSL, if those two images are voxel-aligned, it should be safe to overwrite the s/q forms of your `mni2subj` image with those of the `anat` image, using the `fslcpgeom` command, e.g.: `fslcpgeom anat.nii.gz mni2subj.nii.gz`.
