### ISSUE TITLE
Can open FSLeyes from terminal, but no icon is seen in utilities (macOS Monterey)

### ISSUE THREAD

**Issue by JohannaHeu** [pauldmccarthy/fsleyes#96]
Hi :)

I have a problem. I installed FSL on my Mac including XQuartz. Everything is working fine from the terminal. But there is one problem: I cannot see the icon FSLeyes in my Utilities folder. Moreover, when I open FSLeyes from the terminal (which is working fine) the icon is named "python" and not "FSLeyes". 

When I search it on my Mac FSLeyes is saved in a folder called "fslpython". 
When I move the application from this folder manually to applications, I am not able to open as there is an error saying: file incomplete or damaged

Is there maybe a trick so I can see the icon in my applications too? 

Thanks a lot!
Greetings
Johanna

**Comment by pauldmccarthy** [comment]
Hi @JohannaHeu, sorry for the delay. You should be able to copy  `$FSLDIR/fslpython/envs/fslpython/bin/FSLeyes.app` folder  into your `/Applications/` folder, e.g.:

```
cp -r $FSLDIR/fslpython/envs/fslpython/bin/FSLeyes.app /Applicatiions/
```

> Moreover, when I open FSLeyes from the terminal (which is working fine) the icon is named "python" and not "FSLeyes"

There's nothing I can do about this at the moment, I'm afraid - it's to do with how macOS/GUI apps are distributed as conda packages.

**Comment by JohannaHeu** [comment]
Thank you so much 
.. I think I now found the issue. Always when I call fsleyes in my terminal it opens an fsleyes but from another directory than from the directory you just gave me.

I found the fsleyes application in the direction you wrote and was able to copy it into my applications. But now when I call fsleyes from the terminal it will open the other fsleyes from the directory: usr/local/fsl/fslpython/envs/fslpython/python
so as much as I understand, it does not take the right direction. 

Is there any way I can change this, so that I will call the right application from my terminal as well? 

Thank you!

**Comment by pauldmccarthy** [comment]
Hi @JohannaHeu, unless you have installed FSLeyes independently of your FSL installation, they will both be calling the same version - the `FSLeyes.app` directory just contains a simple script which calls the version of FSLeyes that is installed in `$FSLDIR`.

If you have installed FSLeyes separately (e.g. by running `pip install fsleyes` or `conda install -c conda-forge fsleyes`), you will need to figure out which python environment you have installed it into, and remove it.
