### ISSUE TITLE
Unable to initialise OpenGL!

### ISSUE THREAD

**Issue by soichih** [pauldmccarthy/fsleyes#98]
Hello. I am not sure what I did but fsleyes stopped working on my Ubuntu 21.10 desktop PC (Using X - not wayland).

```
$fsleyes --version
fsleyes/FSLeyes version 1.3.3

$ fsleyes
   ERROR              main.py  590: initialise      - Unable to initialise OpenGL!
NotImplementedError
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/fsleyes/main.py", line 587, in initialise
    fslgl.getGLContext(ready=realCallback)
  File "/usr/local/lib/python3.9/dist-packages/fsleyes/gl/__init__.py", line 490, in getGLContext
    thismod._glContext = GLContext(**kwargs)
  File "/usr/local/lib/python3.9/dist-packages/fsleyes/gl/__init__.py", line 658, in __init__
    self.__createWXGLCanvas()
  File "/usr/local/lib/python3.9/dist-packages/fsleyes/gl/__init__.py", line 804, in __createWXGLCanvas
    attrs = WXGLCanvasTarget.displayAttributes()
  File "/usr/local/lib/python3.9/dist-packages/fsleyes/gl/__init__.py", line 1097, in displayAttributes
    attrs = wxgl.GLAttributes()
SystemError: <class 'wx._glcanvas.GLAttributes'> returned a result with an error set

```

glxinfo shows that it's working fine

```
$ glxinfo
name of display: :1
display: :1  screen: 0
direct rendering: Yes
server glx vendor string: NVIDIA Corporation
server glx version string: 1.4
server glx extensions:
```

Could someone help me troubleshoot this problem?

**Comment by pauldmccarthy** [comment]
Hi @soichih, what version of wxPython do you have installed, and did you install it from https://extras.wxpython.org/ ?

If you are using a newer version of wxPython, it may have been compiled to use EGL rather than GLX for GL initialisation, which (afaik) is not possible when using X11. You may need to downgrade your wxPython version to 4.0.7 if you want to continue using X11. In the future this may become a run-time, rather than compile-time choice - you can read more about it [here](https://github.com/wxWidgets/Phoenix/issues/1923).

**Comment by pauldmccarthy** [comment]
Oh, you may also need to set a `PYOPENGL_PLATFORM=x11` environment variable as well, depending on which version of PyOpenGL you have installed.

**Comment by soichih** [comment]
I had wxPython 4.1.1 installed, and tried to downgrade it to 4.0.7 but I can't get it compiled (with pip3 install wxPython==4.0.7) on my machine (Ubuntu 21.10)

```
(looong output)

ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-tze2arv_/wxpython_01d01d506a7f428984e64a1ce15c2f94/setup.py'"'"'; __file__='"'"'/tmp/pip-install-tze2arv_/wxpython_01d01d506a7f428984e64a1ce15c2f94/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-ks2wgpgq/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.9/wxPython Check the logs for full command output.
```

**Comment by raamana** [comment]
just wanted to say I also have the same issue on macOS 12.3.1, and would appreciate any fixes.

**Comment by pauldmccarthy** [comment]
@raamana would you be able to open a new issue?

@soichih -  https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-21.10/ is not a valid URL - binary wheels are only available for LTS releases. You can see what's available simply by browsing 
the https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ site.

Your first `pip install` command just ended up installing 4.1.1 from your local cache. Do you remember how you installed wxpython in the first place?

In your second `pip install` command, you tried to install a python 3.7 wheel into a python 3.9 environment. Unfortunately there don't seem to be 3.9 wheels available for 4.0.7. 

I'm afraid I can only recommend using [mini]conda - it makes installation much more straightforward. You will continue to run in to problems like this when using pip, unless you are willing to change your OS, or set up your system so that it is able to compile wxpython from source.

**Comment by pauldmccarthy** [comment]
Or you could switch over to Wayland ...

**Comment by soichih** [comment]
I've installed it via conda and I was able to get it to work. It took about 12 hours to install fsleyes on conda. I don't like using conda as it's super slow.. but in this case it seems like I don't have an option. 

Most of the screen capturing software OBS Studio / Zoom / Fireshot etc.. don't support Wayland so that's not an option for me either.

**Comment by pauldmccarthy** [comment]
That sounds excessive - it shouldn't take more than a couple of minutes (assuming you have a good internet connection). There might be something up with your conda configuration, which is causing it to struggle to resolve the environment (e.g. you will have problems if you have `defaults` at a higher priority than `conda-forge`)

**Comment by raamana** [comment]
Hi @soichih, did you figure out a workaround?

Hi Paul, I am happy to open another issue if its warranted, but what I encounter is the the same error discussed here, even on the latest fsleyes 1.7.3 on macOS 13:

```
(base) $ 09:34:39 Quark-2 visualqc >>  fsleyes
Traceback (most recent call last):
  File "/Users/Reddy/anaconda3/envs/py36/lib/python3.7/site-packages/OpenGL/platform/darwin.py", line 38, in GL
    mode=ctypes.RTLD_GLOBAL
  File "/Users/Reddy/anaconda3/envs/py36/lib/python3.7/site-packages/OpenGL/platform/ctypesloader.py", line 36, in loadLibrary
    return _loadLibraryWindows(dllType, name, mode)
  File "/Users/Reddy/anaconda3/envs/py36/lib/python3.7/site-packages/OpenGL/platform/ctypesloader.py", line 89, in _loadLibraryWindows
    return dllType( name, mode )
  File "/Users/Reddy/anaconda3/envs/py36/lib/python3.7/ctypes/__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: ("dlopen(OpenGL, 0x000A): tried: '/Applications/freesurfer/7.2.0/lib/gcc/lib/OpenGL' (no such file), 'OpenGL' (no such file), '/System/Volumes/Preboot/Cryptexes/OSOpenGL' (no such file), '/Users/Reddy/anaconda3/envs/py36/lib/OpenGL' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/Reddy/anaconda3/envs/py36/lib/OpenGL' (no such file), '/Users/Reddy/anaconda3/envs/py36/lib/OpenGL' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/Reddy/anaconda3/envs/py36/lib/OpenGL' (no such file), '/Users/Reddy/anaconda3/envs/py36/lib/OpenGL' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/Reddy/anaconda3/envs/py36/lib/OpenGL' (no such file), '/Users/Reddy/anaconda3/envs/py36/lib/python3.7/lib-dynload/../../OpenGL' (no such file), '/Users/Reddy/anaconda3/envs/py36/lib/OpenGL' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/Reddy/anaconda3/envs/py36/lib/OpenGL' (no such file), '/Users/Reddy/anaconda3/envs/py36/lib/OpenGL' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/Reddy/anaconda3/envs/py36/lib/OpenGL' (no such file), '/Users/Reddy/anaconda3/envs/py36/bin/../lib/OpenGL' (no such file), '/usr/lib/OpenGL' (no such file, not in dyld cache), 'OpenGL' (no such file), '/usr/local/lib/OpenGL' (no such file), '/usr/lib/OpenGL' (no such file, not in dyld cache)", 'OpenGL', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Reddy/anaconda3/envs/py36/bin/fsleyes", line 8, in <module>
    sys.exit(main())
  File "/Users/Reddy/anaconda3/envs/py36/lib/python3.7/site-packages/fsleyes/filtermain.py", line 212, in main
    result = fm.main(args)
  File "/Users/Reddy/anaconda3/envs/py36/lib/python3.7/site-packages/fsleyes/main.py", line 238, in main
    fsleyes.initialise()
  File "/Users/Reddy/anaconda3/envs/py36/lib/python3.7/site-packages/fsleyes/__init__.py", line 243, in initialise
    import fsleyes.plugins as plugins
  File "/Users/Reddy/anaconda3/envs/py36/lib/python3.7/site-packages/fsleyes/plugins/__init__.py", line 196, in <module>
    import fsleyes.views.canvaspanel     as canvaspanel
  File "/Users/Reddy/anaconda3/envs/py36/lib/python3.7/site-packages/fsleyes/views/canvaspanel.py", line 20, in <module>
    from . import                    colourbarpanel
  File "/Users/Reddy/anaconda3/envs/py36/lib/python3.7/site-packages/fsleyes/views/colourbarpanel.py", line 15, in <module>
    import fsleyes.gl.wxglcolourbarcanvas as cbarcanvas
  File "/Users/Reddy/anaconda3/envs/py36/lib/python3.7/site-packages/fsleyes/gl/wxglcolourbarcanvas.py", line 17, in <module>
    import fsleyes.gl.colourbarcanvas as cbarcanvas
  File "/Users/Reddy/anaconda3/envs/py36/lib/python3.7/site-packages/fsleyes/gl/colourbarcanvas.py", line 21, in <module>
    import OpenGL.GL as gl
  File "/Users/Reddy/anaconda3/envs/py36/lib/python3.7/site-packages/OpenGL/GL/__init__.py", line 3, in <module>
    from OpenGL import error as _error
  File "/Users/Reddy/anaconda3/envs/py36/lib/python3.7/site-packages/OpenGL/error.py", line 12, in <module>
    from OpenGL import platform, _configflags
  File "/Users/Reddy/anaconda3/envs/py36/lib/python3.7/site-packages/OpenGL/platform/__init__.py", line 36, in <module>
    _load()
  File "/Users/Reddy/anaconda3/envs/py36/lib/python3.7/site-packages/OpenGL/platform/__init__.py", line 33, in _load
    plugin.install(globals())
  File "/Users/Reddy/anaconda3/envs/py36/lib/python3.7/site-packages/OpenGL/platform/baseplatform.py", line 97, in install
    namespace[ name ] = getattr(self,name,None)
  File "/Users/Reddy/anaconda3/envs/py36/lib/python3.7/site-packages/OpenGL/platform/baseplatform.py", line 15, in __get__
    value = self.fget( obj )
  File "/Users/Reddy/anaconda3/envs/py36/lib/python3.7/site-packages/OpenGL/platform/darwin.py", line 62, in GetCurrentContext
    return self.CGL.CGLGetCurrentContext
  File "/Users/Reddy/anaconda3/envs/py36/lib/python3.7/site-packages/OpenGL/platform/baseplatform.py", line 15, in __get__
    value = self.fget( obj )
  File "/Users/Reddy/anaconda3/envs/py36/lib/python3.7/site-packages/OpenGL/platform/darwin.py", line 45, in CGL
    def CGL(self): return self.GL
  File "/Users/Reddy/anaconda3/envs/py36/lib/python3.7/site-packages/OpenGL/platform/baseplatform.py", line 15, in __get__
    value = self.fget( obj )
  File "/Users/Reddy/anaconda3/envs/py36/lib/python3.7/site-packages/OpenGL/platform/darwin.py", line 41, in GL
    raise ImportError("Unable to load OpenGL library", *err.args)
ImportError: ('Unable to load OpenGL library', "dlopen(OpenGL, 0x000A): tried: '/Applications/freesurfer/7.2.0/lib/gcc/lib/OpenGL' (no such file), 'OpenGL' (no such file), '/System/Volumes/Preboot/Cryptexes/OSOpenGL' (no such file), '/Users/Reddy/anaconda3/envs/py36/lib/OpenGL' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/Reddy/anaconda3/envs/py36/lib/OpenGL' (no such file), '/Users/Reddy/anaconda3/envs/py36/lib/OpenGL' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/Reddy/anaconda3/envs/py36/lib/OpenGL' (no such file), '/Users/Reddy/anaconda3/envs/py36/lib/OpenGL' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/Reddy/anaconda3/envs/py36/lib/OpenGL' (no such file), '/Users/Reddy/anaconda3/envs/py36/lib/python3.7/lib-dynload/../../OpenGL' (no such file), '/Users/Reddy/anaconda3/envs/py36/lib/OpenGL' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/Reddy/anaconda3/envs/py36/lib/OpenGL' (no such file), '/Users/Reddy/anaconda3/envs/py36/lib/OpenGL' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/Reddy/anaconda3/envs/py36/lib/OpenGL' (no such file), '/Users/Reddy/anaconda3/envs/py36/bin/../lib/OpenGL' (no such file), '/usr/lib/OpenGL' (no such file, not in dyld cache), 'OpenGL' (no such file), '/usr/local/lib/OpenGL' (no such file), '/usr/lib/OpenGL' (no such file, not in dyld cache)", 'OpenGL', None)
```

**Comment by pauldmccarthy** [comment]
Hi @raamana can you double check the version of FSLeyes that you are using? The latest FSLeyes version is 1.5.0.

Your issue is completely unrelated to the original issue here -  your issue is due to the fact that macOS versions Big Sur and newer now remove certain shared `.dylib` files from the file system, and instead place them into an in-memory cache. macOS then intercepts `dlopen` calls which refer to the full file path, and loads the files from the cache. This is incompatible with the method that Python 3.7 and older use to load shared libraries on macOS. 

The Python folk [implemented a solution](https://github.com/python/cpython/pull/22855), but (afaik) this has only been implemented in Python 3.8 and newer. I added [a hack](https://github.com/conda-forge/fsleyes-feedstock/blob/main/recipe/opengl.patch) to the conda-forge FSLeyes package which should have resolved it for older versions of Python. 
 
So in principle all you should have to do is install a newer version of FSLeyes from conda-forge, or to create an environment with a newer Python (3.8 or newer).

**Comment by raamana** [comment]
Thanks for taking a look Paul - I am using the latest fsleyes 1.5.0 with python 3.7.2. Let me try conda forge version and newer 3.8.10 python. I will open a new issue if that doesn't work.

**Comment by pauldmccarthy** [comment]
In that case it seems that the hack I mentioned is not working for you (I only have limited access to macOS hardware to test these sorts of things). It does also appear that you may have some relevant environment variables set, e.g. `DYLD_LIBRARY_PATH`. Can you paste the output of `env|sort`?

**Comment by pauldmccarthy** [comment]
(note that the hack is only implemented for the conda-forge FSLeyes package - if you have installed FSLeyes via pip, then you will still be affected by the underlying dylib issue)

**Comment by martin3000** [comment]
$ pip list|grep wx
wxPython                    4.2.2
$ fsleyes --version
fsleyes/FSLeyes version 1.13.0

fsleyes -v
   DEBUG          settings.py  201: write           - Writing fsleyes/fsleyes.notebook.port: 8888
   ERROR              main.py  594: initialise      - Unable to initialise OpenGL!
NotImplementedError
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/jms/.local/lib/python3.12/site-packages/fsleyes/main.py", line 590, in initialise
    fslgl.getGLContext(ready=realCallback,
  File "/home/jms/.local/lib/python3.12/site-packages/fsleyes/gl/__init__.py", line 567, in getGLContext
    thismod._glContext = GLContext(**kwargs)
                         ^^^^^^^^^^^^^^^^^^^
  File "/home/jms/.local/lib/python3.12/site-packages/fsleyes/gl/__init__.py", line 750, in __init__
    self.__createWXGLCanvas()
  File "/home/jms/.local/lib/python3.12/site-packages/fsleyes/gl/__init__.py", line 907, in __createWXGLCanvas
    attrs = WXGLCanvasTarget.displayAttributes()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jms/.local/lib/python3.12/site-packages/fsleyes/gl/__init__.py", line 1226, in displayAttributes
    attrs = wxgl.GLAttributes()
            ^^^^^^^^^^^^^^^^^^^
SystemError: <class 'wx._glcanvas.GLAttributes'> returned a result with an exception set
   DEBUG          settings.py  418: writeConfigFile - Writing fsleyes configuration to: /home/jms/.config/fsleyes/config.pkl


$ glxinfo -B
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Intel (0x8086)
    Device: Mesa Intel(R) HD Graphics 530 (SKL GT2) (0x1912)
    Version: 24.0.9
    Accelerated: yes
    Video memory: 31966MB
    Unified memory: yes
    Preferred profile: core (0x1)
    Max core profile version: 4.6
    Max compat profile version: 4.6
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
OpenGL vendor string: Intel
OpenGL renderer string: Mesa Intel(R) HD Graphics 530 (SKL GT2)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 24.0.9-0ubuntu0.3
OpenGL core profile shading language version string: 4.60
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.6 (Compatibility Profile) Mesa 24.0.9-0ubuntu0.3
OpenGL shading language version string: 4.60
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile

OpenGL ES profile version string: OpenGL ES 3.2 Mesa 24.0.9-0ubuntu0.3
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20

**Comment by pauldmccarthy** [comment]
Hi @martin3000, how did you install wxpyrthon?

**Comment by martin3000** [comment]
AFAIK wxpython was installed together with fsleyes by pip.

**Comment by pauldmccarthy** [comment]
Hi @martin3000, I tend to recommend conda over pip, as it is much easier to support from my end. I can't reproduce this on Ubuntu 22.04+Wayland (I don't have access to a 24.04 machine at the moment). 

Depending on the wxPython build you have installed, you may need to set or unset the `GDK_BACKEND` environment variable, as the choice of GLX or EGL is a compile-time choice. Can you share the output of running `env`?
